2026-03-31T23:50:24.945-07:00  INFO 13925 --- [restful-webservices] [restartedMain] c.e.r.RestfulWebservicesApplication      : Starting RestfulWebservicesApplication using Java 21.0.5 with PID 13925 (/Users/pranavsangu/Documents/Vscode/java/spring_vscode/restful-webservices/target/classes started by pranavsangu in /Users/pranavsangu/Documents/Vscode/java/spring_vscode/restful-webservices)
2026-03-31T23:50:24.946-07:00  INFO 13925 --- [restful-webservices] [restartedMain] c.e.r.RestfulWebservicesApplication      : No active profile set, falling back to 1 default profile: "default"
2026-03-31T23:50:24.946-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.boot.SpringApplication               : Loading source class com.example_web_services.restful_webservices.RestfulWebservicesApplication
2026-03-31T23:50:24.947-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.server.servlet.context.AnnotationConfigServletWebServerApplicationContext@554157f6
2026-03-31T23:50:24.947-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor'
2026-03-31T23:50:24.948-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.internalCachingMetadataReaderFactory'
2026-03-31T23:50:24.951-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.c.a.ClassPathBeanDefinitionScanner   : Identified candidate component class: file [/Users/pranavsangu/Documents/Vscode/java/spring_vscode/restful-webservices/target/classes/com/example_web_services/restful_webservices/HelloWorld/HelloWorldController.class]
2026-03-31T23:50:25.022-07:00  INFO 13925 --- [restful-webservices] [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2026-03-31T23:50:25.022-07:00  INFO 13925 --- [restful-webservices] [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JDBC repositories in DEFAULT mode.
2026-03-31T23:50:25.023-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.AutoConfigurationPackages'
2026-03-31T23:50:25.024-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.a.AutoConfigurationPackages        : @EnableAutoConfiguration was declared on a class in the package 'com.example_web_services.restful_webservices'. Automatic @Repository and @Entity scanning is enabled.
2026-03-31T23:50:25.024-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Scanning for JDBC repositories in packages com.example_web_services.restful_webservices.
2026-03-31T23:50:25.025-07:00  INFO 13925 --- [restful-webservices] [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 0 ms. Found 0 JDBC repository interfaces.
2026-03-31T23:50:25.033-07:00  INFO 13925 --- [restful-webservices] [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2026-03-31T23:50:25.034-07:00  INFO 13925 --- [restful-webservices] [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2026-03-31T23:50:25.035-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Scanning for JPA repositories in packages com.example_web_services.restful_webservices.
2026-03-31T23:50:25.036-07:00  INFO 13925 --- [restful-webservices] [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 1 ms. Found 0 JPA repository interfaces.
2026-03-31T23:50:25.057-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'propertySourcesPlaceholderConfigurer'
2026-03-31T23:50:25.057-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer$DependsOnDatabaseInitializationPostProcessor'
2026-03-31T23:50:25.057-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration$DatabaseShutdownExecutorEntityManagerFactoryDependsOnPostProcessor'
2026-03-31T23:50:25.059-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.context.event.internalEventListenerProcessor'
2026-03-31T23:50:25.060-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'bootstrapExecutorAliasPostProcessor'
2026-03-31T23:50:25.060-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'preserveErrorControllerTargetClassPostProcessor'
2026-03-31T23:50:25.060-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.context.event.internalEventListenerFactory'
2026-03-31T23:50:25.060-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.transaction.config.internalTransactionalEventListenerFactory'
2026-03-31T23:50:25.060-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.context.annotation.internalAutowiredAnnotationProcessor'
2026-03-31T23:50:25.061-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.context.annotation.internalCommonAnnotationProcessor'
2026-03-31T23:50:25.061-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.context.annotation.internalPersistenceAnnotationProcessor'
2026-03-31T23:50:25.061-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor'
2026-03-31T23:50:25.061-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.context.internalConfigurationPropertiesBinder'
2026-03-31T23:50:25.061-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'jdbcConnectionDetailsHikariBeanPostProcessor'
2026-03-31T23:50:25.061-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.aop.config.internalAutoProxyCreator'
2026-03-31T23:50:25.062-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.aop.framework.autoproxy.defaultProxyConfig'
2026-03-31T23:50:25.062-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'persistenceExceptionTranslationPostProcessor'
2026-03-31T23:50:25.063-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'persistenceExceptionTranslationPostProcessor' via factory method to bean named 'environment'
2026-03-31T23:50:25.063-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'projectingArgumentResolverBeanPostProcessor'
2026-03-31T23:50:25.063-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.transaction.config.internalTransactionAdvisor'
2026-03-31T23:50:25.063-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration'
2026-03-31T23:50:25.065-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'transactionAttributeSource'
2026-03-31T23:50:25.065-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'transactionInterceptor'
2026-03-31T23:50:25.065-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'transactionInterceptor' via factory method to bean named 'transactionAttributeSource'
2026-03-31T23:50:25.065-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.transaction.config.internalTransactionAdvisor' via factory method to bean named 'transactionAttributeSource'
2026-03-31T23:50:25.065-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.transaction.config.internalTransactionAdvisor' via factory method to bean named 'transactionInterceptor'
2026-03-31T23:50:25.065-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'webServerFactoryCustomizerBeanPostProcessor'
2026-03-31T23:50:25.065-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'errorPageRegistrarBeanPostProcessor'
2026-03-31T23:50:25.065-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'tomcatServletWebServerFactory'
2026-03-31T23:50:25.065-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.tomcat.autoconfigure.servlet.TomcatServletWebServerAutoConfiguration'
2026-03-31T23:50:25.066-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'server.tomcat-org.springframework.boot.tomcat.autoconfigure.TomcatServerProperties'
2026-03-31T23:50:25.066-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.context.properties.BoundConfigurationProperties'
2026-03-31T23:50:25.067-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.tomcat.autoconfigure.servlet.TomcatServletWebServerAutoConfiguration' via constructor to bean named 'server.tomcat-org.springframework.boot.tomcat.autoconfigure.TomcatServerProperties'
2026-03-31T23:50:25.067-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'servletWebServerFactoryCustomizer'
2026-03-31T23:50:25.067-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.web.server.autoconfigure.servlet.ServletWebServerConfiguration'
2026-03-31T23:50:25.067-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'server-org.springframework.boot.web.server.autoconfigure.ServerProperties'
2026-03-31T23:50:25.068-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'servletWebServerFactoryCustomizer' via factory method to bean named 'server-org.springframework.boot.web.server.autoconfigure.ServerProperties'
2026-03-31T23:50:25.069-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'sslBundleRegistry'
2026-03-31T23:50:25.069-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.ssl.SslAutoConfiguration'
2026-03-31T23:50:25.069-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.ssl-org.springframework.boot.autoconfigure.ssl.SslProperties'
2026-03-31T23:50:25.069-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.autoconfigure.ssl.SslAutoConfiguration' via constructor to bean named 'org.springframework.boot.web.server.servlet.context.AnnotationConfigServletWebServerApplicationContext@554157f6'
2026-03-31T23:50:25.069-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.autoconfigure.ssl.SslAutoConfiguration' via constructor to bean named 'spring.ssl-org.springframework.boot.autoconfigure.ssl.SslProperties'
2026-03-31T23:50:25.069-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'sslPropertiesSslBundleRegistrar'
2026-03-31T23:50:25.069-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'fileWatcher'
2026-03-31T23:50:25.069-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'sslPropertiesSslBundleRegistrar' via factory method to bean named 'fileWatcher'
2026-03-31T23:50:25.070-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'webSocketWebServerCustomizer'
2026-03-31T23:50:25.070-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.tomcat.autoconfigure.TomcatWebServerConfiguration$TomcatWebSocketConfiguration'
2026-03-31T23:50:25.070-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'tomcatWebServerFactoryCustomizer'
2026-03-31T23:50:25.070-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.tomcat.autoconfigure.TomcatWebServerConfiguration'
2026-03-31T23:50:25.070-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.web-org.springframework.boot.autoconfigure.web.WebProperties'
2026-03-31T23:50:25.072-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'tomcatWebServerFactoryCustomizer' via factory method to bean named 'environment'
2026-03-31T23:50:25.072-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'tomcatWebServerFactoryCustomizer' via factory method to bean named 'server-org.springframework.boot.web.server.autoconfigure.ServerProperties'
2026-03-31T23:50:25.072-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'tomcatWebServerFactoryCustomizer' via factory method to bean named 'server.tomcat-org.springframework.boot.tomcat.autoconfigure.TomcatServerProperties'
2026-03-31T23:50:25.072-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'tomcatWebServerFactoryCustomizer' via factory method to bean named 'spring.web-org.springframework.boot.autoconfigure.web.WebProperties'
2026-03-31T23:50:25.072-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'tomcatServletWebServerFactoryCustomizer'
2026-03-31T23:50:25.072-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'tomcatServletWebServerFactoryCustomizer' via factory method to bean named 'server.tomcat-org.springframework.boot.tomcat.autoconfigure.TomcatServerProperties'
2026-03-31T23:50:25.073-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'errorPageCustomizer'
2026-03-31T23:50:25.073-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.webmvc.autoconfigure.error.ErrorMvcAutoConfiguration'
2026-03-31T23:50:25.073-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.webmvc.autoconfigure.error.ErrorMvcAutoConfiguration' via constructor to bean named 'spring.web-org.springframework.boot.autoconfigure.web.WebProperties'
2026-03-31T23:50:25.073-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'dispatcherServletRegistration'
2026-03-31T23:50:25.073-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.webmvc.autoconfigure.DispatcherServletAutoConfiguration$DispatcherServletRegistrationConfiguration'
2026-03-31T23:50:25.074-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'dispatcherServlet'
2026-03-31T23:50:25.074-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.webmvc.autoconfigure.DispatcherServletAutoConfiguration$DispatcherServletConfiguration'
2026-03-31T23:50:25.074-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.mvc-org.springframework.boot.webmvc.autoconfigure.WebMvcProperties'
2026-03-31T23:50:25.075-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'dispatcherServlet' via factory method to bean named 'spring.mvc-org.springframework.boot.webmvc.autoconfigure.WebMvcProperties'
2026-03-31T23:50:25.076-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'dispatcherServletRegistration' via factory method to bean named 'dispatcherServlet'
2026-03-31T23:50:25.076-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'dispatcherServletRegistration' via factory method to bean named 'spring.mvc-org.springframework.boot.webmvc.autoconfigure.WebMvcProperties'
2026-03-31T23:50:25.076-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'multipartConfigElement'
2026-03-31T23:50:25.076-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.servlet.autoconfigure.MultipartAutoConfiguration'
2026-03-31T23:50:25.076-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.servlet.multipart-org.springframework.boot.servlet.autoconfigure.MultipartProperties'
2026-03-31T23:50:25.077-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.servlet.autoconfigure.MultipartAutoConfiguration' via constructor to bean named 'spring.servlet.multipart-org.springframework.boot.servlet.autoconfigure.MultipartProperties'
2026-03-31T23:50:25.077-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'errorPageCustomizer' via factory method to bean named 'dispatcherServletRegistration'
2026-03-31T23:50:25.078-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.t.s.TomcatServletWebServerFactory  : Code archive: /Users/pranavsangu/.m2/repository/org/springframework/boot/spring-boot-web-server/4.0.4/spring-boot-web-server-4.0.4.jar
2026-03-31T23:50:25.078-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.t.s.TomcatServletWebServerFactory  : Code archive: /Users/pranavsangu/.m2/repository/org/springframework/boot/spring-boot-web-server/4.0.4/spring-boot-web-server-4.0.4.jar
2026-03-31T23:50:25.078-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.t.s.TomcatServletWebServerFactory  : None of the document roots [src/main/webapp, public, static] point to a directory and will be ignored.
2026-03-31T23:50:25.083-07:00  INFO 13925 --- [restful-webservices] [restartedMain] o.s.boot.tomcat.TomcatWebServer          : Tomcat initialized with port 8080 (http)
2026-03-31T23:50:25.084-07:00  INFO 13925 --- [restful-webservices] [restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2026-03-31T23:50:25.084-07:00  INFO 13925 --- [restful-webservices] [restartedMain] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/11.0.18]
2026-03-31T23:50:25.090-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] b.w.c.s.WebApplicationContextInitializer : Published root WebApplicationContext as ServletContext attribute with name [org.springframework.web.context.WebApplicationContext.ROOT]
2026-03-31T23:50:25.090-07:00  INFO 13925 --- [restful-webservices] [restartedMain] b.w.c.s.WebApplicationContextInitializer : Root WebApplicationContext: initialization completed in 143 ms
2026-03-31T23:50:25.091-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'h2Console'
2026-03-31T23:50:25.091-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.h2console.autoconfigure.H2ConsoleAutoConfiguration'
2026-03-31T23:50:25.091-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.h2.console-org.springframework.boot.h2console.autoconfigure.H2ConsoleProperties'
2026-03-31T23:50:25.091-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.h2console.autoconfigure.H2ConsoleAutoConfiguration' via constructor to bean named 'spring.h2.console-org.springframework.boot.h2console.autoconfigure.H2ConsoleProperties'
2026-03-31T23:50:25.092-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'requestContextFilter'
2026-03-31T23:50:25.092-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'formContentFilter'
2026-03-31T23:50:25.092-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.webmvc.autoconfigure.WebMvcAutoConfiguration'
2026-03-31T23:50:25.093-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'characterEncodingFilter'
2026-03-31T23:50:25.093-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.servlet.autoconfigure.HttpEncodingAutoConfiguration'
2026-03-31T23:50:25.093-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.servlet.encoding-org.springframework.boot.servlet.autoconfigure.ServletEncodingProperties'
2026-03-31T23:50:25.094-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'characterEncodingFilter' via factory method to bean named 'spring.servlet.encoding-org.springframework.boot.servlet.autoconfigure.ServletEncodingProperties'
2026-03-31T23:50:25.094-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.w.s.ServletContextInitializerBeans : Mapping filters: characterEncodingFilter urls=[/*] order=-2147483648, formContentFilter urls=[/*] order=-9900, requestContextFilter urls=[/*] order=-105
2026-03-31T23:50:25.095-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.w.s.ServletContextInitializerBeans : Mapping servlets: dispatcherServlet urls=[/], h2Console urls=[/h2-console/*]
2026-03-31T23:50:25.095-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.s.f.OrderedRequestContextFilter    : Filter 'requestContextFilter' configured for use
2026-03-31T23:50:25.095-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.s.f.OrderedCharacterEncodingFilter : Filter 'characterEncodingFilter' configured for use
2026-03-31T23:50:25.095-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.s.filter.OrderedFormContentFilter  : Filter 'formContentFilter' configured for use
2026-03-31T23:50:25.096-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'applicationTaskExecutor'
2026-03-31T23:50:25.096-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.task.TaskExecutorConfigurations$TaskExecutorConfiguration'
2026-03-31T23:50:25.096-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'threadPoolTaskExecutorBuilder'
2026-03-31T23:50:25.096-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.task.TaskExecutorConfigurations$ThreadPoolTaskExecutorBuilderConfiguration'
2026-03-31T23:50:25.097-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.task.execution-org.springframework.boot.autoconfigure.task.TaskExecutionProperties'
2026-03-31T23:50:25.098-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'threadPoolTaskExecutorBuilder' via factory method to bean named 'spring.task.execution-org.springframework.boot.autoconfigure.task.TaskExecutionProperties'
2026-03-31T23:50:25.098-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'applicationTaskExecutor' via factory method to bean named 'threadPoolTaskExecutorBuilder'
2026-03-31T23:50:25.098-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2026-03-31T23:50:25.101-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'dataSourceScriptDatabaseInitializer'
2026-03-31T23:50:25.101-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.jdbc.autoconfigure.DataSourceInitializationAutoConfiguration'
2026-03-31T23:50:25.103-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'dataSource'
2026-03-31T23:50:25.103-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.jdbc.autoconfigure.DataSourceConfiguration$Hikari'
2026-03-31T23:50:25.105-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.datasource-org.springframework.boot.jdbc.autoconfigure.DataSourceProperties'
2026-03-31T23:50:25.111-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'jdbcConnectionDetails'
2026-03-31T23:50:25.111-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration$PooledDataSourceConfiguration'
2026-03-31T23:50:25.111-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jdbcConnectionDetails' via factory method to bean named 'spring.datasource-org.springframework.boot.jdbc.autoconfigure.DataSourceProperties'
2026-03-31T23:50:25.112-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'dataSource' via factory method to bean named 'spring.datasource-org.springframework.boot.jdbc.autoconfigure.DataSourceProperties'
2026-03-31T23:50:25.113-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'dataSource' via factory method to bean named 'jdbcConnectionDetails'
2026-03-31T23:50:25.113-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'dataSource' via factory method to bean named 'environment'
2026-03-31T23:50:25.122-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.sql.init-org.springframework.boot.sql.autoconfigure.init.SqlInitializationProperties'
2026-03-31T23:50:25.123-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'dataSourceScriptDatabaseInitializer' via factory method to bean named 'dataSource'
2026-03-31T23:50:25.123-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'dataSourceScriptDatabaseInitializer' via factory method to bean named 'spring.sql.init-org.springframework.boot.sql.autoconfigure.init.SqlInitializationProperties'
2026-03-31T23:50:25.125-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'inMemoryDatabaseShutdownExecutor'
2026-03-31T23:50:25.125-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration'
2026-03-31T23:50:25.127-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'inMemoryDatabaseShutdownExecutor' via factory method to bean named 'dataSource'
2026-03-31T23:50:25.127-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'inMemoryDatabaseShutdownExecutor' via factory method to bean named 'spring.datasource-org.springframework.boot.jdbc.autoconfigure.DataSourceProperties'
2026-03-31T23:50:25.127-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'entityManagerFactory'
2026-03-31T23:50:25.127-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.hibernate.autoconfigure.HibernateJpaConfiguration'
2026-03-31T23:50:25.127-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.jpa-org.springframework.boot.jpa.autoconfigure.JpaProperties'
2026-03-31T23:50:25.128-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.jpa.hibernate-org.springframework.boot.hibernate.autoconfigure.HibernateProperties'
2026-03-31T23:50:25.129-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.hibernate.autoconfigure.HibernateJpaConfiguration' via constructor to bean named 'dataSource'
2026-03-31T23:50:25.129-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.hibernate.autoconfigure.HibernateJpaConfiguration' via constructor to bean named 'spring.jpa-org.springframework.boot.jpa.autoconfigure.JpaProperties'
2026-03-31T23:50:25.129-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.hibernate.autoconfigure.HibernateJpaConfiguration' via constructor to bean named 'org.springframework.beans.factory.support.DefaultListableBeanFactory@68495b5a'
2026-03-31T23:50:25.129-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.hibernate.autoconfigure.HibernateJpaConfiguration' via constructor to bean named 'spring.jpa.hibernate-org.springframework.boot.hibernate.autoconfigure.HibernateProperties'
2026-03-31T23:50:25.129-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'hikariPoolDataSourceMetadataProvider'
2026-03-31T23:50:25.129-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.jdbc.autoconfigure.DataSourcePoolMetadataProvidersConfiguration$HikariPoolDataSourceMetadataProviderConfiguration'
2026-03-31T23:50:25.131-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'entityManagerFactoryBuilder'
2026-03-31T23:50:25.131-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'jpaVendorAdapter'
2026-03-31T23:50:25.132-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'entityManagerFactoryBuilder' via factory method to bean named 'jpaVendorAdapter'
2026-03-31T23:50:25.132-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'persistenceManagedTypes'
2026-03-31T23:50:25.133-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'persistenceManagedTypes' via factory method to bean named 'org.springframework.beans.factory.support.DefaultListableBeanFactory@68495b5a'
2026-03-31T23:50:25.133-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'persistenceManagedTypes' via factory method to bean named 'org.springframework.boot.web.server.servlet.context.AnnotationConfigServletWebServerApplicationContext@554157f6'
2026-03-31T23:50:25.138-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'entityManagerFactory' via factory method to bean named 'entityManagerFactoryBuilder'
2026-03-31T23:50:25.139-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'entityManagerFactory' via factory method to bean named 'persistenceManagedTypes'
2026-03-31T23:50:25.139-07:00  INFO 13925 --- [restful-webservices] [restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-6 - Starting...
2026-03-31T23:50:25.143-07:00  INFO 13925 --- [restful-webservices] [restartedMain] com.zaxxer.hikari.pool.HikariPool        : HikariPool-6 - Added connection conn50: url=jdbc:h2:mem:6edf2ea4-a93b-457d-a1d0-7a896202590a user=SA
2026-03-31T23:50:25.143-07:00  INFO 13925 --- [restful-webservices] [restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-6 - Start completed.
2026-03-31T23:50:25.144-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] j.LocalContainerEntityManagerFactoryBean : Building JPA container EntityManagerFactory for persistence unit 'default'
2026-03-31T23:50:25.145-07:00  INFO 13925 --- [restful-webservices] [restartedMain] org.hibernate.orm.jpa                    : HHH008540: Processing PersistenceUnitInfo [name: default]
2026-03-31T23:50:25.146-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.o.jpa.hibernate.SpringBeanContainer  : Falling back to Hibernate's default producer after bean creation failure for interface org.hibernate.engine.jdbc.connections.spi.MultiTenantConnectionProvider: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.hibernate.engine.jdbc.connections.spi.MultiTenantConnectionProvider': Failed to instantiate [org.hibernate.engine.jdbc.connections.spi.MultiTenantConnectionProvider]: Specified class is an interface
2026-03-31T23:50:25.166-07:00  INFO 13925 --- [restful-webservices] [restartedMain] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
2026-03-31T23:50:25.167-07:00  INFO 13925 --- [restful-webservices] [restartedMain] org.hibernate.orm.connections.pooling    : HHH10001005: Database info:
	Database JDBC URL [jdbc:h2:mem:6edf2ea4-a93b-457d-a1d0-7a896202590a]
	Database driver: H2 JDBC Driver
	Database dialect: H2Dialect
	Database version: 2.4.240
	Default catalog/schema: 6EDF2EA4-A93B-457D-A1D0-7A896202590A/PUBLIC
	Autocommit mode: undefined/unknown
	Isolation level: READ_COMMITTED [default READ_COMMITTED]
	JDBC fetch size: 100
	Pool: DataSourceConnectionProvider
	Minimum pool size: undefined/unknown
	Maximum pool size: undefined/unknown
2026-03-31T23:50:25.168-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.o.jpa.hibernate.SpringBeanContainer  : Falling back to Hibernate's default producer after bean creation failure for interface org.hibernate.context.spi.CurrentTenantIdentifierResolver: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.hibernate.context.spi.CurrentTenantIdentifierResolver<?>' available
2026-03-31T23:50:25.168-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.o.jpa.hibernate.SpringBeanContainer  : Falling back to Hibernate's default producer after bean creation failure for interface org.hibernate.context.spi.TenantSchemaMapper: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.hibernate.context.spi.TenantSchemaMapper<?>' available
2026-03-31T23:50:25.184-07:00  INFO 13925 --- [restful-webservices] [restartedMain] org.hibernate.orm.core                   : HHH000489: No JTA platform available (set 'hibernate.transaction.jta.platform' to enable JTA platform integration)
2026-03-31T23:50:25.184-07:00  INFO 13925 --- [restful-webservices] [restartedMain] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2026-03-31T23:50:25.196-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'restfulWebservicesApplication'
2026-03-31T23:50:25.196-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'helloWorldController'
2026-03-31T23:50:25.196-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration'
2026-03-31T23:50:25.196-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.context.properties.EnableConfigurationPropertiesRegistrar.methodValidationExcludeFilter'
2026-03-31T23:50:25.197-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.webmvc.autoconfigure.DispatcherServletAutoConfiguration'
2026-03-31T23:50:25.197-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.task.TaskExecutorConfigurations$SimpleAsyncTaskExecutorBuilderConfiguration'
2026-03-31T23:50:25.198-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.autoconfigure.task.TaskExecutorConfigurations$SimpleAsyncTaskExecutorBuilderConfiguration' via constructor to bean named 'spring.task.execution-org.springframework.boot.autoconfigure.task.TaskExecutionProperties'
2026-03-31T23:50:25.198-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'simpleAsyncTaskExecutorBuilder'
2026-03-31T23:50:25.198-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.task.TaskExecutorConfigurations$AsyncConfigurerConfiguration'
2026-03-31T23:50:25.198-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'applicationTaskExecutorAsyncConfigurer'
2026-03-31T23:50:25.198-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'applicationTaskExecutorAsyncConfigurer' via factory method to bean named 'org.springframework.beans.factory.support.DefaultListableBeanFactory@68495b5a'
2026-03-31T23:50:25.199-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.task.TaskExecutorConfigurations$BootstrapExecutorConfiguration'
2026-03-31T23:50:25.199-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration'
2026-03-31T23:50:25.199-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.webmvc.autoconfigure.error.ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration'
2026-03-31T23:50:25.199-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'error'
2026-03-31T23:50:25.199-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'beanNameViewResolver'
2026-03-31T23:50:25.199-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.webmvc.autoconfigure.error.ErrorMvcAutoConfiguration$DefaultErrorViewResolverConfiguration'
2026-03-31T23:50:25.199-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.webmvc.autoconfigure.error.ErrorMvcAutoConfiguration$DefaultErrorViewResolverConfiguration' via constructor to bean named 'org.springframework.boot.web.server.servlet.context.AnnotationConfigServletWebServerApplicationContext@554157f6'
2026-03-31T23:50:25.199-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.webmvc.autoconfigure.error.ErrorMvcAutoConfiguration$DefaultErrorViewResolverConfiguration' via constructor to bean named 'spring.web-org.springframework.boot.autoconfigure.web.WebProperties'
2026-03-31T23:50:25.199-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'conventionErrorViewResolver'
2026-03-31T23:50:25.199-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'errorAttributes'
2026-03-31T23:50:25.200-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'basicErrorController'
2026-03-31T23:50:25.200-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'basicErrorController' via factory method to bean named 'errorAttributes'
2026-03-31T23:50:25.200-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.webmvc.autoconfigure.WebMvcAutoConfiguration$EnableWebMvcConfiguration'
2026-03-31T23:50:25.200-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.webmvc.autoconfigure.WebMvcAutoConfiguration$EnableWebMvcConfiguration' via constructor to bean named 'spring.mvc-org.springframework.boot.webmvc.autoconfigure.WebMvcProperties'
2026-03-31T23:50:25.201-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.webmvc.autoconfigure.WebMvcAutoConfiguration$EnableWebMvcConfiguration' via constructor to bean named 'spring.web-org.springframework.boot.autoconfigure.web.WebProperties'
2026-03-31T23:50:25.201-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.webmvc.autoconfigure.WebMvcAutoConfiguration$EnableWebMvcConfiguration' via constructor to bean named 'org.springframework.beans.factory.support.DefaultListableBeanFactory@68495b5a'
2026-03-31T23:50:25.202-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.webmvc.autoconfigure.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter'
2026-03-31T23:50:25.202-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.webmvc.autoconfigure.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter' via constructor to bean named 'spring.web-org.springframework.boot.autoconfigure.web.WebProperties'
2026-03-31T23:50:25.202-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.webmvc.autoconfigure.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter' via constructor to bean named 'spring.mvc-org.springframework.boot.webmvc.autoconfigure.WebMvcProperties'
2026-03-31T23:50:25.202-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.webmvc.autoconfigure.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter' via constructor to bean named 'org.springframework.beans.factory.support.DefaultListableBeanFactory@68495b5a'
2026-03-31T23:50:25.202-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.data.web.config.SpringDataWebConfiguration'
2026-03-31T23:50:25.202-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.data.web.config.SpringDataWebConfiguration' via constructor to bean named 'org.springframework.boot.web.server.servlet.context.AnnotationConfigServletWebServerApplicationContext@554157f6'
2026-03-31T23:50:25.203-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'openEntityManagerInViewInterceptorConfigurer'
2026-03-31T23:50:25.203-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.jpa.autoconfigure.JpaBaseConfiguration$JpaWebConfiguration'
2026-03-31T23:50:25.203-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.jpa.autoconfigure.JpaBaseConfiguration$JpaWebConfiguration' via constructor to bean named 'spring.jpa-org.springframework.boot.jpa.autoconfigure.JpaProperties'
2026-03-31T23:50:25.203-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'openEntityManagerInViewInterceptor'
2026-03-31T23:50:25.203-07:00  WARN 13925 --- [restful-webservices] [restartedMain] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2026-03-31T23:50:25.204-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'openEntityManagerInViewInterceptorConfigurer' via factory method to bean named 'openEntityManagerInViewInterceptor'
2026-03-31T23:50:25.204-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'welcomePageHandlerMapping'
2026-03-31T23:50:25.205-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'mvcConversionService'
2026-03-31T23:50:25.208-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'mvcResourceUrlProvider'
2026-03-31T23:50:25.208-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'welcomePageHandlerMapping' via factory method to bean named 'org.springframework.boot.web.server.servlet.context.AnnotationConfigServletWebServerApplicationContext@554157f6'
2026-03-31T23:50:25.208-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'welcomePageHandlerMapping' via factory method to bean named 'mvcConversionService'
2026-03-31T23:50:25.208-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'welcomePageHandlerMapping' via factory method to bean named 'mvcResourceUrlProvider'
2026-03-31T23:50:25.209-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'welcomePageNotAcceptableHandlerMapping'
2026-03-31T23:50:25.209-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'welcomePageNotAcceptableHandlerMapping' via factory method to bean named 'org.springframework.boot.web.server.servlet.context.AnnotationConfigServletWebServerApplicationContext@554157f6'
2026-03-31T23:50:25.209-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'welcomePageNotAcceptableHandlerMapping' via factory method to bean named 'mvcConversionService'
2026-03-31T23:50:25.209-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'welcomePageNotAcceptableHandlerMapping' via factory method to bean named 'mvcResourceUrlProvider'
2026-03-31T23:50:25.210-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'localeResolver'
2026-03-31T23:50:25.210-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'flashMapManager'
2026-03-31T23:50:25.210-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'viewNameTranslator'
2026-03-31T23:50:25.210-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'mvcValidator'
2026-03-31T23:50:25.210-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'requestMappingHandlerMapping'
2026-03-31T23:50:25.210-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'mvcContentNegotiationManager'
2026-03-31T23:50:25.211-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'stringHttpMessageConvertersCustomizer'
2026-03-31T23:50:25.211-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.http.converter.autoconfigure.HttpMessageConvertersAutoConfiguration$StringHttpMessageConverterConfiguration'
2026-03-31T23:50:25.211-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.http.converters-org.springframework.boot.http.converter.autoconfigure.HttpMessageConvertersProperties'
2026-03-31T23:50:25.211-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'stringHttpMessageConvertersCustomizer' via factory method to bean named 'spring.http.converters-org.springframework.boot.http.converter.autoconfigure.HttpMessageConvertersProperties'
2026-03-31T23:50:25.211-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'jacksonJsonHttpMessageConvertersCustomizer'
2026-03-31T23:50:25.211-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.http.converter.autoconfigure.JacksonHttpMessageConvertersConfiguration$JacksonJsonHttpMessageConverterConfiguration'
2026-03-31T23:50:25.211-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'jacksonJsonMapper'
2026-03-31T23:50:25.211-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.jackson.autoconfigure.JacksonAutoConfiguration'
2026-03-31T23:50:25.212-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'problemDetailJsonMapperBuilderCustomizer'
2026-03-31T23:50:25.212-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.jackson.autoconfigure.JacksonAutoConfiguration$JsonProblemDetailsConfiguration'
2026-03-31T23:50:25.212-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'standardJsonMapperBuilderCustomizer'
2026-03-31T23:50:25.212-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.jackson.autoconfigure.JacksonAutoConfiguration$JacksonJsonMapperBuilderCustomizerConfiguration'
2026-03-31T23:50:25.212-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.jackson-org.springframework.boot.jackson.autoconfigure.JacksonProperties'
2026-03-31T23:50:25.212-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'standardJsonMapperBuilderCustomizer' via factory method to bean named 'spring.jackson-org.springframework.boot.jackson.autoconfigure.JacksonProperties'
2026-03-31T23:50:25.213-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'jackson3GeoModule'
2026-03-31T23:50:25.213-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.data.web.config.SpringDataJackson3Configuration'
2026-03-31T23:50:25.213-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'springDataWebSettings'
2026-03-31T23:50:25.213-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.data.autoconfigure.web.DataWebAutoConfiguration'
2026-03-31T23:50:25.213-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.data.web-org.springframework.boot.data.autoconfigure.web.DataWebProperties'
2026-03-31T23:50:25.213-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.data.autoconfigure.web.DataWebAutoConfiguration' via constructor to bean named 'spring.data.web-org.springframework.boot.data.autoconfigure.web.DataWebProperties'
2026-03-31T23:50:25.214-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'jackson3pageModule'
2026-03-31T23:50:25.214-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'jacksonMixinModule'
2026-03-31T23:50:25.214-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.jackson.autoconfigure.JacksonAutoConfiguration$JacksonMixinConfiguration'
2026-03-31T23:50:25.214-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'jacksonMixinModuleEntries'
2026-03-31T23:50:25.214-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jacksonMixinModuleEntries' via factory method to bean named 'org.springframework.boot.web.server.servlet.context.AnnotationConfigServletWebServerApplicationContext@554157f6'
2026-03-31T23:50:25.214-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jacksonMixinModule' via factory method to bean named 'org.springframework.boot.web.server.servlet.context.AnnotationConfigServletWebServerApplicationContext@554157f6'
2026-03-31T23:50:25.214-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jacksonMixinModule' via factory method to bean named 'jacksonMixinModuleEntries'
2026-03-31T23:50:25.215-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'jsonComponentModule'
2026-03-31T23:50:25.215-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jsonMapperBuilder' via factory method to bean named 'problemDetailJsonMapperBuilderCustomizer'
2026-03-31T23:50:25.215-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jsonMapperBuilder' via factory method to bean named 'standardJsonMapperBuilderCustomizer'
2026-03-31T23:50:25.216-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jacksonJsonMapper' via factory method to bean named 'jsonMapperBuilder'
2026-03-31T23:50:25.216-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jacksonJsonHttpMessageConvertersCustomizer' via factory method to bean named 'jacksonJsonMapper'
2026-03-31T23:50:25.216-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'serverConvertersCustomizer'
2026-03-31T23:50:25.216-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.http.converter.autoconfigure.HttpMessageConvertersAutoConfiguration'
2026-03-31T23:50:25.217-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'mvcApiVersionStrategy'
2026-03-31T23:50:25.218-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'requestMappingHandlerMapping' via factory method to bean named 'mvcContentNegotiationManager'
2026-03-31T23:50:25.218-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'requestMappingHandlerMapping' via factory method to bean named 'mvcApiVersionStrategy'
2026-03-31T23:50:25.218-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'requestMappingHandlerMapping' via factory method to bean named 'mvcConversionService'
2026-03-31T23:50:25.218-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'requestMappingHandlerMapping' via factory method to bean named 'mvcResourceUrlProvider'
2026-03-31T23:50:25.221-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] s.w.s.m.m.a.RequestMappingHandlerMapping : 5 mappings in 'requestMappingHandlerMapping'
2026-03-31T23:50:25.221-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'mvcPatternParser'
2026-03-31T23:50:25.221-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'mvcUrlPathHelper'
2026-03-31T23:50:25.222-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'mvcPathMatcher'
2026-03-31T23:50:25.222-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'viewControllerHandlerMapping'
2026-03-31T23:50:25.222-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'viewControllerHandlerMapping' via factory method to bean named 'mvcConversionService'
2026-03-31T23:50:25.222-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'viewControllerHandlerMapping' via factory method to bean named 'mvcResourceUrlProvider'
2026-03-31T23:50:25.222-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'beanNameHandlerMapping'
2026-03-31T23:50:25.222-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'beanNameHandlerMapping' via factory method to bean named 'mvcConversionService'
2026-03-31T23:50:25.222-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'beanNameHandlerMapping' via factory method to bean named 'mvcResourceUrlProvider'
2026-03-31T23:50:25.223-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'routerFunctionMapping'
2026-03-31T23:50:25.223-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'routerFunctionMapping' via factory method to bean named 'mvcConversionService'
2026-03-31T23:50:25.223-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'routerFunctionMapping' via factory method to bean named 'mvcResourceUrlProvider'
2026-03-31T23:50:25.223-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'routerFunctionMapping' via factory method to bean named 'mvcApiVersionStrategy'
2026-03-31T23:50:25.223-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'resourceHandlerMapping'
2026-03-31T23:50:25.224-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'resourceHandlerMapping' via factory method to bean named 'mvcContentNegotiationManager'
2026-03-31T23:50:25.224-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'resourceHandlerMapping' via factory method to bean named 'mvcConversionService'
2026-03-31T23:50:25.224-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'resourceHandlerMapping' via factory method to bean named 'mvcResourceUrlProvider'
2026-03-31T23:50:25.224-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.w.s.handler.SimpleUrlHandlerMapping  : Patterns [/webjars/**, /**] in 'resourceHandlerMapping'
2026-03-31T23:50:25.224-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'defaultServletHandlerMapping'
2026-03-31T23:50:25.224-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'requestMappingHandlerAdapter'
2026-03-31T23:50:25.225-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'requestMappingHandlerAdapter' via factory method to bean named 'mvcContentNegotiationManager'
2026-03-31T23:50:25.225-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'requestMappingHandlerAdapter' via factory method to bean named 'mvcConversionService'
2026-03-31T23:50:25.225-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'requestMappingHandlerAdapter' via factory method to bean named 'mvcValidator'
2026-03-31T23:50:25.225-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'sortResolver'
2026-03-31T23:50:25.225-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'sortCustomizer'
2026-03-31T23:50:25.225-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'pageableResolver'
2026-03-31T23:50:25.225-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'pageableCustomizer'
2026-03-31T23:50:25.226-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] s.w.s.m.m.a.RequestMappingHandlerAdapter : ControllerAdvice beans: 0 @ModelAttribute, 0 @InitBinder, 2 RequestBodyAdvice, 1 ResponseBodyAdvice
2026-03-31T23:50:25.226-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'mvcViewResolver'
2026-03-31T23:50:25.226-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'mvcViewResolver' via factory method to bean named 'mvcContentNegotiationManager'
2026-03-31T23:50:25.227-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'defaultViewResolver'
2026-03-31T23:50:25.227-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'viewResolver'
2026-03-31T23:50:25.227-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'viewResolver' via factory method to bean named 'org.springframework.beans.factory.support.DefaultListableBeanFactory@68495b5a'
2026-03-31T23:50:25.227-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'viewResolver'
2026-03-31T23:50:25.227-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'handlerFunctionAdapter'
2026-03-31T23:50:25.227-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'mvcUriComponentsContributor'
2026-03-31T23:50:25.227-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'mvcUriComponentsContributor' via factory method to bean named 'mvcConversionService'
2026-03-31T23:50:25.227-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'mvcUriComponentsContributor' via factory method to bean named 'requestMappingHandlerAdapter'
2026-03-31T23:50:25.227-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'httpRequestHandlerAdapter'
2026-03-31T23:50:25.228-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'simpleControllerHandlerAdapter'
2026-03-31T23:50:25.228-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'handlerExceptionResolver'
2026-03-31T23:50:25.228-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'handlerExceptionResolver' via factory method to bean named 'mvcContentNegotiationManager'
2026-03-31T23:50:25.228-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] .m.m.a.ExceptionHandlerExceptionResolver : ControllerAdvice beans: 0 @ExceptionHandler, 1 ResponseBodyAdvice
2026-03-31T23:50:25.228-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.aop.AopAutoConfiguration$AspectJAutoProxyingConfiguration$CglibAutoProxyConfiguration'
2026-03-31T23:50:25.228-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.aop.AopAutoConfiguration$AspectJAutoProxyingConfiguration'
2026-03-31T23:50:25.228-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.aop.AopAutoConfiguration'
2026-03-31T23:50:25.228-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.availability.ApplicationAvailabilityAutoConfiguration'
2026-03-31T23:50:25.228-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'applicationAvailability'
2026-03-31T23:50:25.228-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.context.ConfigurationPropertiesAutoConfiguration'
2026-03-31T23:50:25.228-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.context.LifecycleAutoConfiguration'
2026-03-31T23:50:25.228-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'lifecycleProcessor'
2026-03-31T23:50:25.229-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.lifecycle-org.springframework.boot.autoconfigure.context.LifecycleProperties'
2026-03-31T23:50:25.229-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'lifecycleProcessor' via factory method to bean named 'spring.lifecycle-org.springframework.boot.autoconfigure.context.LifecycleProperties'
2026-03-31T23:50:25.229-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration'
2026-03-31T23:50:25.229-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.info-org.springframework.boot.autoconfigure.info.ProjectInfoProperties'
2026-03-31T23:50:25.229-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration' via constructor to bean named 'spring.info-org.springframework.boot.autoconfigure.info.ProjectInfoProperties'
2026-03-31T23:50:25.229-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.task.TaskSchedulingConfigurations$ThreadPoolTaskSchedulerBuilderConfiguration'
2026-03-31T23:50:25.230-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'threadPoolTaskSchedulerBuilder'
2026-03-31T23:50:25.230-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.task.scheduling-org.springframework.boot.autoconfigure.task.TaskSchedulingProperties'
2026-03-31T23:50:25.230-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'threadPoolTaskSchedulerBuilder' via factory method to bean named 'spring.task.scheduling-org.springframework.boot.autoconfigure.task.TaskSchedulingProperties'
2026-03-31T23:50:25.230-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.task.TaskSchedulingConfigurations$SimpleAsyncTaskSchedulerBuilderConfiguration'
2026-03-31T23:50:25.231-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.autoconfigure.task.TaskSchedulingConfigurations$SimpleAsyncTaskSchedulerBuilderConfiguration' via constructor to bean named 'spring.task.scheduling-org.springframework.boot.autoconfigure.task.TaskSchedulingProperties'
2026-03-31T23:50:25.231-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'simpleAsyncTaskSchedulerBuilder'
2026-03-31T23:50:25.231-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.task.TaskSchedulingAutoConfiguration'
2026-03-31T23:50:25.231-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.data.web.config.ProjectingArgumentResolverRegistrar'
2026-03-31T23:50:25.231-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'offsetResolver'
2026-03-31T23:50:25.231-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.transaction.jta.autoconfigure.JtaAutoConfiguration'
2026-03-31T23:50:25.232-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.jdbc.autoconfigure.DataSourcePoolMetadataProvidersConfiguration'
2026-03-31T23:50:25.232-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration'
2026-03-31T23:50:25.232-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.jdbc.autoconfigure.JdbcTemplateConfiguration'
2026-03-31T23:50:25.232-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'jdbcTemplate'
2026-03-31T23:50:25.232-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.jdbc-org.springframework.boot.jdbc.autoconfigure.JdbcProperties'
2026-03-31T23:50:25.232-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jdbcTemplate' via factory method to bean named 'dataSource'
2026-03-31T23:50:25.232-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jdbcTemplate' via factory method to bean named 'spring.jdbc-org.springframework.boot.jdbc.autoconfigure.JdbcProperties'
2026-03-31T23:50:25.232-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.jdbc.autoconfigure.NamedParameterJdbcTemplateConfiguration'
2026-03-31T23:50:25.232-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'namedParameterJdbcTemplate'
2026-03-31T23:50:25.233-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'namedParameterJdbcTemplate' via factory method to bean named 'jdbcTemplate'
2026-03-31T23:50:25.233-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.jdbc.autoconfigure.JdbcTemplateAutoConfiguration'
2026-03-31T23:50:25.233-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.transaction.autoconfigure.TransactionManagerCustomizationAutoConfiguration'
2026-03-31T23:50:25.233-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'platformTransactionManagerCustomizers'
2026-03-31T23:50:25.233-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'transactionExecutionListeners'
2026-03-31T23:50:25.233-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.transaction-org.springframework.boot.transaction.autoconfigure.TransactionProperties'
2026-03-31T23:50:25.234-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.jpa.autoconfigure.JpaBaseConfiguration$PersistenceManagedTypesConfiguration'
2026-03-31T23:50:25.234-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'transactionManager'
2026-03-31T23:50:25.234-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration'
2026-03-31T23:50:25.234-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.jdbc.autoconfigure.DataSourceTransactionManagerAutoConfiguration$JdbcTransactionManagerConfiguration'
2026-03-31T23:50:25.234-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.jdbc.autoconfigure.DataSourceTransactionManagerAutoConfiguration'
2026-03-31T23:50:25.234-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.data.jdbc.autoconfigure.DataJdbcRepositoriesAutoConfiguration$SpringBootJdbcConfiguration'
2026-03-31T23:50:25.234-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.data.jdbc-org.springframework.boot.data.jdbc.autoconfigure.DataJdbcProperties'
2026-03-31T23:50:25.234-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.data.jdbc.autoconfigure.DataJdbcRepositoriesAutoConfiguration$SpringBootJdbcConfiguration' via constructor to bean named 'org.springframework.boot.web.server.servlet.context.AnnotationConfigServletWebServerApplicationContext@554157f6'
2026-03-31T23:50:25.234-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.data.jdbc.autoconfigure.DataJdbcRepositoriesAutoConfiguration$SpringBootJdbcConfiguration' via constructor to bean named 'spring.data.jdbc-org.springframework.boot.data.jdbc.autoconfigure.DataJdbcProperties'
2026-03-31T23:50:25.234-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'jdbcManagedTypes'
2026-03-31T23:50:25.235-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'jdbcMappingContext'
2026-03-31T23:50:25.235-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'jdbcCustomConversions'
2026-03-31T23:50:25.235-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'jdbcDialect'
2026-03-31T23:50:25.235-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jdbcDialect' via factory method to bean named 'namedParameterJdbcTemplate'
2026-03-31T23:50:25.235-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.jdbc.datasource.DataSourceUtils      : Fetching JDBC Connection from DataSource
2026-03-31T23:50:25.238-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.sql.Timestamp to class java.time.LocalDateTime as reading converter
2026-03-31T23:50:25.238-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.sql.Timestamp to class java.time.LocalDate as reading converter
2026-03-31T23:50:25.238-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.time.LocalDate to class java.sql.Timestamp as writing converter
2026-03-31T23:50:25.238-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.sql.Timestamp to class java.time.LocalTime as reading converter
2026-03-31T23:50:25.238-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.time.LocalTime to class java.sql.Timestamp as writing converter
2026-03-31T23:50:25.238-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.sql.Timestamp to class java.time.Instant as reading converter
2026-03-31T23:50:25.238-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.time.Instant to class java.sql.Timestamp as writing converter
2026-03-31T23:50:25.238-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.util.Date to class java.time.LocalDateTime as reading converter
2026-03-31T23:50:25.238-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.time.LocalDateTime to class java.util.Date as writing converter
2026-03-31T23:50:25.238-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.util.Date to class java.time.LocalDate as reading converter
2026-03-31T23:50:25.238-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.time.LocalDate to class java.util.Date as writing converter
2026-03-31T23:50:25.238-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.util.Date to class java.time.LocalTime as reading converter
2026-03-31T23:50:25.238-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.time.LocalTime to class java.util.Date as writing converter
2026-03-31T23:50:25.238-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.util.Date to class java.time.Instant as reading converter
2026-03-31T23:50:25.238-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.time.Instant to class java.util.Date as writing converter
2026-03-31T23:50:25.238-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.time.LocalDateTime to class java.time.Instant as reading converter
2026-03-31T23:50:25.238-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.time.Instant to class java.time.LocalDateTime as reading converter
2026-03-31T23:50:25.238-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.time.ZoneId to class java.lang.String as writing converter
2026-03-31T23:50:25.239-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.lang.String to class java.time.ZoneId as reading converter
2026-03-31T23:50:25.239-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.time.Duration to class java.lang.String as writing converter
2026-03-31T23:50:25.239-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.lang.String to class java.time.Duration as reading converter
2026-03-31T23:50:25.239-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.time.Period to class java.lang.String as writing converter
2026-03-31T23:50:25.239-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.lang.String to class java.time.Period as reading converter
2026-03-31T23:50:25.239-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.lang.String to class java.time.LocalDate as reading converter
2026-03-31T23:50:25.239-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.lang.String to class java.time.LocalDateTime as reading converter
2026-03-31T23:50:25.239-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.data.convert.CustomConversions       : Adding converter from class java.lang.String to class java.time.Instant as reading converter
2026-03-31T23:50:25.239-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jdbcMappingContext' via factory method to bean named 'jdbcCustomConversions'
2026-03-31T23:50:25.239-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jdbcMappingContext' via factory method to bean named 'jdbcManagedTypes'
2026-03-31T23:50:25.239-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'jdbcConverter'
2026-03-31T23:50:25.241-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jdbcConverter' via factory method to bean named 'jdbcMappingContext'
2026-03-31T23:50:25.241-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jdbcConverter' via factory method to bean named 'namedParameterJdbcTemplate'
2026-03-31T23:50:25.241-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jdbcConverter' via factory method to bean named 'jdbcCustomConversions'
2026-03-31T23:50:25.241-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jdbcConverter' via factory method to bean named 'jdbcDialect'
2026-03-31T23:50:25.241-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'jdbcAggregateTemplate'
2026-03-31T23:50:25.241-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'dataAccessStrategyBean'
2026-03-31T23:50:25.241-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'dataAccessStrategyBean' via factory method to bean named 'namedParameterJdbcTemplate'
2026-03-31T23:50:25.241-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'dataAccessStrategyBean' via factory method to bean named 'jdbcConverter'
2026-03-31T23:50:25.241-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'dataAccessStrategyBean' via factory method to bean named 'jdbcMappingContext'
2026-03-31T23:50:25.241-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'dataAccessStrategyBean' via factory method to bean named 'jdbcDialect'
2026-03-31T23:50:25.242-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jdbcAggregateTemplate' via factory method to bean named 'org.springframework.boot.web.server.servlet.context.AnnotationConfigServletWebServerApplicationContext@554157f6'
2026-03-31T23:50:25.242-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jdbcAggregateTemplate' via factory method to bean named 'jdbcMappingContext'
2026-03-31T23:50:25.242-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jdbcAggregateTemplate' via factory method to bean named 'jdbcConverter'
2026-03-31T23:50:25.242-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jdbcAggregateTemplate' via factory method to bean named 'dataAccessStrategyBean'
2026-03-31T23:50:25.242-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'idGeneratingBeforeSaveCallback'
2026-03-31T23:50:25.242-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'idGeneratingBeforeSaveCallback' via factory method to bean named 'jdbcMappingContext'
2026-03-31T23:50:25.242-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'idGeneratingBeforeSaveCallback' via factory method to bean named 'namedParameterJdbcTemplate'
2026-03-31T23:50:25.242-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'idGeneratingBeforeSaveCallback' via factory method to bean named 'jdbcDialect'
2026-03-31T23:50:25.242-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.data.jdbc.autoconfigure.DataJdbcRepositoriesAutoConfiguration$JdbcRepositoriesConfiguration'
2026-03-31T23:50:25.242-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'data-jdbc.repository-aot-processor#0'
2026-03-31T23:50:25.243-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.data.jdbc.autoconfigure.DataJdbcRepositoriesAutoConfiguration'
2026-03-31T23:50:25.243-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.data.jpa.autoconfigure.DataJpaRepositoriesAutoConfiguration'
2026-03-31T23:50:25.243-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'eagerJpaMetamodelCacheCleanup'
2026-03-31T23:50:25.243-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'jpaSharedEM_entityManagerFactory'
2026-03-31T23:50:25.244-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.data.jpa.util.JpaMetamodelCacheCleanup'
2026-03-31T23:50:25.244-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.data.jpa.repository.support.JpaEvaluationContextExtension'
2026-03-31T23:50:25.245-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'data-jpa.repository-aot-processor#0'
2026-03-31T23:50:25.245-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration$DatabaseShutdownExecutorEntityManagerFactoryDependsOnConfiguration'
2026-03-31T23:50:25.245-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfiguration$RestartConfiguration'
2026-03-31T23:50:25.245-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'spring.devtools-org.springframework.boot.devtools.autoconfigure.DevToolsProperties'
2026-03-31T23:50:25.245-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfiguration$RestartConfiguration' via constructor to bean named 'spring.devtools-org.springframework.boot.devtools.autoconfigure.DevToolsProperties'
2026-03-31T23:50:25.245-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'restartingClassPathChangedEventListener'
2026-03-31T23:50:25.245-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'fileSystemWatcherFactory'
2026-03-31T23:50:25.245-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'restartingClassPathChangedEventListener' via factory method to bean named 'fileSystemWatcherFactory'
2026-03-31T23:50:25.246-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'classPathFileSystemWatcher'
2026-03-31T23:50:25.246-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'classPathRestartStrategy'
2026-03-31T23:50:25.246-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'classPathFileSystemWatcher' via factory method to bean named 'fileSystemWatcherFactory'
2026-03-31T23:50:25.246-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'classPathFileSystemWatcher' via factory method to bean named 'classPathRestartStrategy'
2026-03-31T23:50:25.246-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'conditionEvaluationDeltaLoggingListener'
2026-03-31T23:50:25.246-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfiguration'
2026-03-31T23:50:25.246-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'h2ConsoleLogger'
2026-03-31T23:50:25.246-07:00  INFO 13925 --- [restful-webservices] [restartedMain] o.s.b.h.a.H2ConsoleAutoConfiguration     : H2 console available at '/h2-console'. Database available at 'jdbc:h2:mem:6edf2ea4-a93b-457d-a1d0-7a896202590a'
2026-03-31T23:50:25.246-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.http.converter.autoconfigure.JacksonHttpMessageConvertersConfiguration'
2026-03-31T23:50:25.246-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.http.converter.autoconfigure.Jackson2HttpMessageConvertersConfiguration'
2026-03-31T23:50:25.246-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'clientConvertersCustomizer'
2026-03-31T23:50:25.246-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.jdbc.autoconfigure.JdbcClientAutoConfiguration'
2026-03-31T23:50:25.246-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'jdbcClient'
2026-03-31T23:50:25.247-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'jdbcClient' via factory method to bean named 'namedParameterJdbcTemplate'
2026-03-31T23:50:25.247-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.persistence.autoconfigure.PersistenceExceptionTranslationAutoConfiguration'
2026-03-31T23:50:25.247-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'multipartResolver'
2026-03-31T23:50:25.247-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.transaction.autoconfigure.TransactionAutoConfiguration$EnableTransactionManagementConfiguration$CglibAutoProxyConfiguration'
2026-03-31T23:50:25.247-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.transaction.autoconfigure.TransactionAutoConfiguration$EnableTransactionManagementConfiguration'
2026-03-31T23:50:25.247-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.transaction.autoconfigure.TransactionAutoConfiguration$TransactionTemplateConfiguration'
2026-03-31T23:50:25.247-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'transactionTemplate'
2026-03-31T23:50:25.247-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'transactionTemplate' via factory method to bean named 'transactionManager'
2026-03-31T23:50:25.247-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.transaction.autoconfigure.TransactionAutoConfiguration'
2026-03-31T23:50:25.249-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase -2147483647
2026-03-31T23:50:25.249-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.c.support.DefaultLifecycleProcessor  : Successfully started bean 'springBootLoggingLifecycle'
2026-03-31T23:50:25.249-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 1073741823
2026-03-31T23:50:25.249-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147481599
2026-03-31T23:50:25.250-07:00  INFO 13925 --- [restful-webservices] [restartedMain] o.s.boot.tomcat.TomcatWebServer          : Tomcat started on port 8080 (http) with context path '/'
2026-03-31T23:50:25.250-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.c.support.DefaultLifecycleProcessor  : Successfully started bean 'webServerStartStop'
2026-03-31T23:50:25.250-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147482623
2026-03-31T23:50:25.250-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.c.support.DefaultLifecycleProcessor  : Successfully started bean 'webServerGracefulShutdown'
2026-03-31T23:50:25.251-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] .s.b.a.l.ConditionEvaluationReportLogger : 


============================
CONDITIONS EVALUATION REPORT
============================


Positive matches:
-----------------

   AopAutoConfiguration matched:
      - @ConditionalOnBooleanProperty (spring.aop.auto=true) matched (OnPropertyCondition)

   AopAutoConfiguration.AspectJAutoProxyingConfiguration matched:
      - @ConditionalOnClass found required class 'org.aspectj.weaver.Advice' (OnClassCondition)

   AopAutoConfiguration.AspectJAutoProxyingConfiguration.CglibAutoProxyConfiguration matched:
      - @ConditionalOnBooleanProperty (spring.aop.proxy-target-class=true) matched (OnPropertyCondition)

   ApplicationAvailabilityAutoConfiguration#applicationAvailability matched:
      - @ConditionalOnMissingBean (types: org.springframework.boot.availability.ApplicationAvailability; SearchStrategy: all) did not find any beans (OnBeanCondition)

   DataJdbcRepositoriesAutoConfiguration matched:
      - @ConditionalOnClass found required classes 'org.springframework.jdbc.core.namedparam.NamedParameterJdbcOperations', 'org.springframework.data.jdbc.repository.config.AbstractJdbcConfiguration' (OnClassCondition)
      - @ConditionalOnBooleanProperty (spring.data.jdbc.repositories.enabled=true) matched (OnPropertyCondition)
      - @ConditionalOnBean (types: org.springframework.jdbc.core.namedparam.NamedParameterJdbcOperations,org.springframework.transaction.PlatformTransactionManager; SearchStrategy: all) found beans 'transactionManager', 'namedParameterJdbcTemplate' (OnBeanCondition)

   DataJdbcRepositoriesAutoConfiguration.JdbcRepositoriesConfiguration matched:
      - @ConditionalOnMissingBean (types: org.springframework.data.jdbc.repository.config.JdbcRepositoryConfigExtension; SearchStrategy: all) did not find any beans (OnBeanCondition)

   DataJdbcRepositoriesAutoConfiguration.SpringBootJdbcConfiguration matched:
      - @ConditionalOnMissingBean (types: org.springframework.data.jdbc.repository.config.AbstractJdbcConfiguration; SearchStrategy: all) did not find any beans (OnBeanCondition)

   DataJdbcRepositoriesAutoConfiguration.SpringBootJdbcConfiguration#dataAccessStrategyBean matched:
      - @ConditionalOnMissingBean (types: org.springframework.data.jdbc.core.convert.DataAccessStrategy; SearchStrategy: all) did not find any beans (OnBeanCondition)

   DataJdbcRepositoriesAutoConfiguration.SpringBootJdbcConfiguration#jdbcAggregateTemplate matched:
      - @ConditionalOnMissingBean (types: org.springframework.data.jdbc.core.JdbcAggregateTemplate; SearchStrategy: all) did not find any beans (OnBeanCondition)

   DataJdbcRepositoriesAutoConfiguration.SpringBootJdbcConfiguration#jdbcConverter matched:
      - @ConditionalOnMissingBean (types: org.springframework.data.jdbc.core.convert.JdbcConverter; SearchStrategy: all) did not find any beans (OnBeanCondition)

   DataJdbcRepositoriesAutoConfiguration.SpringBootJdbcConfiguration#jdbcCustomConversions matched:
      - @ConditionalOnMissingBean (types: org.springframework.data.jdbc.core.convert.JdbcCustomConversions; SearchStrategy: all) did not find any beans (OnBeanCondition)

   DataJdbcRepositoriesAutoConfiguration.SpringBootJdbcConfiguration#jdbcDialect matched:
      - @ConditionalOnMissingBean (types: org.springframework.data.jdbc.core.dialect.JdbcDialect; SearchStrategy: all) did not find any beans (OnBeanCondition)

   DataJdbcRepositoriesAutoConfiguration.SpringBootJdbcConfiguration#jdbcManagedTypes matched:
      - @ConditionalOnMissingBean (types: org.springframework.data.relational.RelationalManagedTypes; SearchStrategy: all) did not find any beans (OnBeanCondition)

   DataJdbcRepositoriesAutoConfiguration.SpringBootJdbcConfiguration#jdbcMappingContext matched:
      - @ConditionalOnMissingBean (types: org.springframework.data.jdbc.core.mapping.JdbcMappingContext; SearchStrategy: all) did not find any beans (OnBeanCondition)

   DataJpaRepositoriesAutoConfiguration matched:
      - @ConditionalOnClass found required class 'org.springframework.data.jpa.repository.JpaRepository' (OnClassCondition)
      - @ConditionalOnBooleanProperty (spring.data.jpa.repositories.enabled=true) matched (OnPropertyCondition)
      - @ConditionalOnBean (types: javax.sql.DataSource; SearchStrategy: all) found bean 'dataSource'; @ConditionalOnMissingBean (types: org.springframework.data.jpa.repository.support.JpaRepositoryFactoryBean,org.springframework.data.jpa.repository.config.JpaRepositoryConfigExtension; SearchStrategy: all) did not find any beans (OnBeanCondition)

   DataSourceAutoConfiguration matched:
      - @ConditionalOnClass found required classes 'javax.sql.DataSource', 'org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType' (OnClassCondition)
      - @ConditionalOnMissingBean (types: io.r2dbc.spi.ConnectionFactory; SearchStrategy: all) did not find any beans (OnBeanCondition)

   DataSourceAutoConfiguration.PooledDataSourceConfiguration matched:
      - AnyNestedCondition 1 matched 1 did not; NestedCondition on DataSourceAutoConfiguration.PooledDataSourceCondition.PooledDataSourceAvailable PooledDataSource found supported DataSource; NestedCondition on DataSourceAutoConfiguration.PooledDataSourceCondition.ExplicitType @ConditionalOnProperty (spring.datasource.type) did not find property 'spring.datasource.type' (DataSourceAutoConfiguration.PooledDataSourceCondition)
      - @ConditionalOnMissingBean (types: javax.sql.DataSource,javax.sql.XADataSource; SearchStrategy: all) did not find any beans (OnBeanCondition)

   DataSourceAutoConfiguration.PooledDataSourceConfiguration#jdbcConnectionDetails matched:
      - @ConditionalOnMissingBean (types: org.springframework.boot.jdbc.autoconfigure.JdbcConnectionDetails; SearchStrategy: all) did not find any beans (OnBeanCondition)

   DataSourceConfiguration.Hikari matched:
      - @ConditionalOnClass found required class 'com.zaxxer.hikari.HikariDataSource' (OnClassCondition)
      - @ConditionalOnProperty (spring.datasource.type=com.zaxxer.hikari.HikariDataSource) matched (OnPropertyCondition)
      - @ConditionalOnMissingBean (types: javax.sql.DataSource; SearchStrategy: all) did not find any beans (OnBeanCondition)

   DataSourceInitializationAutoConfiguration matched:
      - @ConditionalOnClass found required class 'org.springframework.jdbc.datasource.init.DatabasePopulator' (OnClassCondition)
      - SQL InitializationDatabase Initialization default value is EMBEDDED (OnSqlInitializationCondition)
      - @ConditionalOnSingleCandidate (types: javax.sql.DataSource; SearchStrategy: all) found a single bean 'dataSource'; @ConditionalOnMissingBean (types: org.springframework.boot.sql.autoconfigure.init.ApplicationScriptDatabaseInitializer; SearchStrategy: all) did not find any beans (OnBeanCondition)

   DataSourcePoolMetadataProvidersConfiguration.HikariPoolDataSourceMetadataProviderConfiguration matched:
      - @ConditionalOnClass found required class 'com.zaxxer.hikari.HikariDataSource' (OnClassCondition)

   DataSourceTransactionManagerAutoConfiguration matched:
      - @ConditionalOnClass found required classes 'javax.sql.DataSource', 'org.springframework.jdbc.core.JdbcTemplate', 'org.springframework.transaction.TransactionManager' (OnClassCondition)

   DataSourceTransactionManagerAutoConfiguration.JdbcTransactionManagerConfiguration matched:
      - @ConditionalOnSingleCandidate (types: javax.sql.DataSource; SearchStrategy: all) found a single bean 'dataSource' (OnBeanCondition)

   DataWebAutoConfiguration matched:
      - @ConditionalOnClass found required classes 'org.springframework.data.web.PageableHandlerMethodArgumentResolver', 'org.springframework.web.servlet.config.annotation.WebMvcConfigurer' (OnClassCondition)
      - found 'session' scope (OnWebApplicationCondition)
      - @ConditionalOnMissingBean (types: org.springframework.data.web.PageableHandlerMethodArgumentResolver; SearchStrategy: all) did not find any beans (OnBeanCondition)

   DataWebAutoConfiguration#pageableCustomizer matched:
      - @ConditionalOnMissingBean (types: org.springframework.data.web.config.PageableHandlerMethodArgumentResolverCustomizer; SearchStrategy: all) did not find any beans (OnBeanCondition)

   DataWebAutoConfiguration#sortCustomizer matched:
      - @ConditionalOnMissingBean (types: org.springframework.data.web.config.SortHandlerMethodArgumentResolverCustomizer; SearchStrategy: all) did not find any beans (OnBeanCondition)

   DataWebAutoConfiguration#springDataWebSettings matched:
      - @ConditionalOnMissingBean (types: org.springframework.data.web.config.SpringDataWebSettings; SearchStrategy: all) did not find any beans (OnBeanCondition)

   DevToolsDataSourceAutoConfiguration matched:
      - @ConditionalOnClass found required class 'javax.sql.DataSource' (OnClassCondition)
      - Devtools devtools enabled. (OnEnabledDevToolsCondition)
      - DevTools DataSource Condition found auto-configured DataSource (DevToolsDataSourceAutoConfiguration.DevToolsDataSourceCondition)

   DevToolsDataSourceAutoConfiguration.DatabaseShutdownExecutorEntityManagerFactoryDependsOnConfiguration matched:
      - @ConditionalOnClass found required classes 'org.springframework.boot.jpa.autoconfigure.EntityManagerFactoryDependsOnPostProcessor', 'org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean' (OnClassCondition)
      - @ConditionalOnBean (types: org.springframework.orm.jpa.AbstractEntityManagerFactoryBean; SearchStrategy: all) found bean '&entityManagerFactory' (OnBeanCondition)

   DispatcherServletAutoConfiguration matched:
      - @ConditionalOnClass found required class 'org.springframework.web.servlet.DispatcherServlet' (OnClassCondition)
      - found 'session' scope (OnWebApplicationCondition)

   DispatcherServletAutoConfiguration.DispatcherServletConfiguration matched:
      - @ConditionalOnClass found required class 'jakarta.servlet.ServletRegistration' (OnClassCondition)
      - Default DispatcherServlet did not find dispatcher servlet beans (DispatcherServletAutoConfiguration.DefaultDispatcherServletCondition)

   DispatcherServletAutoConfiguration.DispatcherServletRegistrationConfiguration matched:
      - @ConditionalOnClass found required class 'jakarta.servlet.ServletRegistration' (OnClassCondition)
      - DispatcherServlet Registration did not find servlet registration bean (DispatcherServletAutoConfiguration.DispatcherServletRegistrationCondition)

   DispatcherServletAutoConfiguration.DispatcherServletRegistrationConfiguration#dispatcherServletRegistration matched:
      - @ConditionalOnBean (names: dispatcherServlet types: org.springframework.web.servlet.DispatcherServlet; SearchStrategy: all) found bean 'dispatcherServlet' (OnBeanCondition)

   ErrorMvcAutoConfiguration matched:
      - @ConditionalOnClass found required classes 'jakarta.servlet.Servlet', 'org.springframework.web.servlet.DispatcherServlet' (OnClassCondition)
      - found 'session' scope (OnWebApplicationCondition)

   ErrorMvcAutoConfiguration#basicErrorController matched:
      - @ConditionalOnMissingBean (types: org.springframework.boot.webmvc.error.ErrorController; SearchStrategy: current) did not find any beans (OnBeanCondition)

   ErrorMvcAutoConfiguration#errorAttributes matched:
      - @ConditionalOnMissingBean (types: org.springframework.boot.webmvc.error.ErrorAttributes; SearchStrategy: current) did not find any beans (OnBeanCondition)

   ErrorMvcAutoConfiguration.DefaultErrorViewResolverConfiguration#conventionErrorViewResolver matched:
      - @ConditionalOnBean (types: org.springframework.web.servlet.DispatcherServlet; SearchStrategy: all) found bean 'dispatcherServlet'; @ConditionalOnMissingBean (types: org.springframework.boot.webmvc.autoconfigure.error.ErrorViewResolver; SearchStrategy: all) did not find any beans (OnBeanCondition)

   ErrorMvcAutoConfiguration.WhitelabelErrorViewConfiguration matched:
      - @ConditionalOnBooleanProperty (spring.web.error.whitelabel.enabled=true) matched (OnPropertyCondition)
      - ErrorTemplate Missing did not find error template view (ErrorMvcAutoConfiguration.ErrorTemplateMissingCondition)

   ErrorMvcAutoConfiguration.WhitelabelErrorViewConfiguration#beanNameViewResolver matched:
      - @ConditionalOnMissingBean (types: org.springframework.web.servlet.view.BeanNameViewResolver; SearchStrategy: all) did not find any beans (OnBeanCondition)

   ErrorMvcAutoConfiguration.WhitelabelErrorViewConfiguration#defaultErrorView matched:
      - @ConditionalOnMissingBean (names: error; SearchStrategy: all) did not find any beans (OnBeanCondition)

   H2ConsoleAutoConfiguration matched:
      - @ConditionalOnClass found required class 'org.h2.server.web.JakartaWebServlet' (OnClassCondition)
      - found 'session' scope (OnWebApplicationCondition)
      - @ConditionalOnBooleanProperty (spring.h2.console.enabled=true) matched (OnPropertyCondition)

   HibernateJpaAutoConfiguration matched:
      - @ConditionalOnClass found required classes 'org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean', 'jakarta.persistence.EntityManager', 'org.hibernate.engine.spi.SessionImplementor' (OnClassCondition)

   HibernateJpaConfiguration matched:
      - @ConditionalOnSingleCandidate (types: javax.sql.DataSource; SearchStrategy: all) found a single bean 'dataSource' (OnBeanCondition)

   HttpEncodingAutoConfiguration matched:
      - @ConditionalOnClass found required class 'org.springframework.web.filter.CharacterEncodingFilter' (OnClassCondition)
      - found 'session' scope (OnWebApplicationCondition)
      - @ConditionalOnBooleanProperty (spring.servlet.encoding.enabled=true) matched (OnPropertyCondition)

   HttpEncodingAutoConfiguration#characterEncodingFilter matched:
      - @ConditionalOnMissingBean (types: org.springframework.web.filter.CharacterEncodingFilter; SearchStrategy: all) did not find any beans (OnBeanCondition)

   HttpMessageConvertersAutoConfiguration matched:
      - @ConditionalOnClass found required class 'org.springframework.http.converter.HttpMessageConverter' (OnClassCondition)
      - NoneNestedConditions 0 matched 1 did not; NestedCondition on HttpMessageConvertersAutoConfiguration.NotReactiveWebApplicationCondition.ReactiveWebApplication did not find reactive web application classes (HttpMessageConvertersAutoConfiguration.NotReactiveWebApplicationCondition)

   HttpMessageConvertersAutoConfiguration.StringHttpMessageConverterConfiguration#stringHttpMessageConvertersCustomizer matched:
      - @ConditionalOnMissingBean (types: org.springframework.http.converter.StringHttpMessageConverter; SearchStrategy: all) did not find any beans (OnBeanCondition)

   JacksonAutoConfiguration matched:
      - @ConditionalOnClass found required class 'tools.jackson.databind.json.JsonMapper' (OnClassCondition)

   JacksonAutoConfiguration#jacksonJsonMapper matched:
      - @ConditionalOnMissingBean (types: tools.jackson.databind.json.JsonMapper; SearchStrategy: all) did not find any beans (OnBeanCondition)

   JacksonAutoConfiguration#jsonMapperBuilder matched:
      - @ConditionalOnMissingBean (types: tools.jackson.databind.json.JsonMapper$Builder; SearchStrategy: all) did not find any beans (OnBeanCondition)

   JacksonAutoConfiguration.JsonProblemDetailsConfiguration matched:
      - @ConditionalOnClass found required class 'org.springframework.http.ProblemDetail' (OnClassCondition)

   JacksonHttpMessageConvertersConfiguration.JacksonJsonHttpMessageConverterConfiguration matched:
      - @ConditionalOnClass found required class 'tools.jackson.databind.json.JsonMapper' (OnClassCondition)
      - @ConditionalOnProperty (spring.http.converters.preferred-json-mapper=jackson) matched (OnPropertyCondition)
      - @ConditionalOnBean (types: tools.jackson.databind.json.JsonMapper; SearchStrategy: all) found bean 'jacksonJsonMapper' (OnBeanCondition)

   JacksonHttpMessageConvertersConfiguration.JacksonJsonHttpMessageConverterConfiguration#jacksonJsonHttpMessageConvertersCustomizer matched:
      - @ConditionalOnMissingBean (types: org.springframework.http.converter.json.JacksonJsonHttpMessageConverter ignored: org.springframework.hateoas.server.mvc.TypeConstrainedJacksonJsonHttpMessageConverter,org.springframework.data.rest.webmvc.alps.AlpsJacksonJsonHttpMessageConverter; SearchStrategy: all) did not find any beans (OnBeanCondition)

   JdbcClientAutoConfiguration matched:
      - @ConditionalOnSingleCandidate (types: org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate; SearchStrategy: all) found a single bean 'namedParameterJdbcTemplate'; @ConditionalOnMissingBean (types: org.springframework.jdbc.core.simple.JdbcClient; SearchStrategy: all) did not find any beans (OnBeanCondition)

   JdbcTemplateAutoConfiguration matched:
      - @ConditionalOnClass found required classes 'javax.sql.DataSource', 'org.springframework.jdbc.core.JdbcTemplate' (OnClassCondition)
      - @ConditionalOnSingleCandidate (types: javax.sql.DataSource; SearchStrategy: all) found a single bean 'dataSource' (OnBeanCondition)

   JdbcTemplateConfiguration matched:
      - @ConditionalOnMissingBean (types: org.springframework.jdbc.core.JdbcOperations; SearchStrategy: all) did not find any beans (OnBeanCondition)

   JpaBaseConfiguration#entityManagerFactory matched:
      - @ConditionalOnMissingBean (types: org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean,jakarta.persistence.EntityManagerFactory; SearchStrategy: all) did not find any beans (OnBeanCondition)

   JpaBaseConfiguration#entityManagerFactoryBuilder matched:
      - @ConditionalOnMissingBean (types: org.springframework.boot.jpa.EntityManagerFactoryBuilder; SearchStrategy: all) did not find any beans (OnBeanCondition)

   JpaBaseConfiguration#jpaVendorAdapter matched:
      - @ConditionalOnMissingBean (types: org.springframework.orm.jpa.JpaVendorAdapter; SearchStrategy: all) did not find any beans (OnBeanCondition)

   JpaBaseConfiguration#transactionManager matched:
      - @ConditionalOnMissingBean (types: org.springframework.transaction.TransactionManager; SearchStrategy: all) did not find any beans (OnBeanCondition)

   JpaBaseConfiguration.JpaWebConfiguration matched:
      - @ConditionalOnClass found required class 'org.springframework.web.servlet.config.annotation.WebMvcConfigurer' (OnClassCondition)
      - found 'session' scope (OnWebApplicationCondition)
      - @ConditionalOnBooleanProperty (spring.jpa.open-in-view=true) matched (OnPropertyCondition)
      - @ConditionalOnMissingBean (types: org.springframework.orm.jpa.support.OpenEntityManagerInViewInterceptor,org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter; SearchStrategy: all) did not find any beans (OnBeanCondition)

   JpaBaseConfiguration.PersistenceManagedTypesConfiguration matched:
      - @ConditionalOnMissingBean (types: org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean,jakarta.persistence.EntityManagerFactory; SearchStrategy: all) did not find any beans (OnBeanCondition)

   JpaBaseConfiguration.PersistenceManagedTypesConfiguration#persistenceManagedTypes matched:
      - @ConditionalOnMissingBean (types: org.springframework.orm.jpa.persistenceunit.PersistenceManagedTypes; SearchStrategy: all) did not find any beans (OnBeanCondition)

   JtaAutoConfiguration matched:
      - @ConditionalOnClass found required class 'jakarta.transaction.Transaction' (OnClassCondition)
      - @ConditionalOnBooleanProperty (spring.jta.enabled=true) matched (OnPropertyCondition)

   LifecycleAutoConfiguration#defaultLifecycleProcessor matched:
      - @ConditionalOnMissingBean (names: lifecycleProcessor; SearchStrategy: current) did not find any beans (OnBeanCondition)

   LocalDevToolsAutoConfiguration matched:
      - Initialized Restarter Condition available and initialized (OnInitializedRestarterCondition)

   LocalDevToolsAutoConfiguration.RestartConfiguration matched:
      - @ConditionalOnBooleanProperty (spring.devtools.restart.enabled=true) matched (OnPropertyCondition)

   LocalDevToolsAutoConfiguration.RestartConfiguration#classPathFileSystemWatcher matched:
      - @ConditionalOnMissingBean (types: org.springframework.boot.devtools.classpath.ClassPathFileSystemWatcher; SearchStrategy: all) did not find any beans (OnBeanCondition)

   LocalDevToolsAutoConfiguration.RestartConfiguration#classPathRestartStrategy matched:
      - @ConditionalOnMissingBean (types: org.springframework.boot.devtools.classpath.ClassPathRestartStrategy; SearchStrategy: all) did not find any beans (OnBeanCondition)

   LocalDevToolsAutoConfiguration.RestartConfiguration#conditionEvaluationDeltaLoggingListener matched:
      - @ConditionalOnBooleanProperty (spring.devtools.restart.log-condition-evaluation-delta=true) matched (OnPropertyCondition)

   MultipartAutoConfiguration matched:
      - @ConditionalOnClass found required classes 'jakarta.servlet.Servlet', 'org.springframework.web.multipart.support.StandardServletMultipartResolver', 'jakarta.servlet.MultipartConfigElement' (OnClassCondition)
      - found 'session' scope (OnWebApplicationCondition)
      - @ConditionalOnBooleanProperty (spring.servlet.multipart.enabled=true) matched (OnPropertyCondition)

   MultipartAutoConfiguration#multipartConfigElement matched:
      - @ConditionalOnMissingBean (types: jakarta.servlet.MultipartConfigElement; SearchStrategy: all) did not find any beans (OnBeanCondition)

   MultipartAutoConfiguration#multipartResolver matched:
      - @ConditionalOnMissingBean (types: org.springframework.web.multipart.MultipartResolver; SearchStrategy: all) did not find any beans (OnBeanCondition)

   NamedParameterJdbcTemplateConfiguration matched:
      - @ConditionalOnSingleCandidate (types: org.springframework.jdbc.core.JdbcTemplate; SearchStrategy: all) found a single bean 'jdbcTemplate'; @ConditionalOnMissingBean (types: org.springframework.jdbc.core.namedparam.NamedParameterJdbcOperations; SearchStrategy: all) did not find any beans (OnBeanCondition)

   PersistenceExceptionTranslationAutoConfiguration matched:
      - @ConditionalOnClass found required class 'org.springframework.dao.annotation.PersistenceExceptionTranslationPostProcessor' (OnClassCondition)

   PersistenceExceptionTranslationAutoConfiguration#persistenceExceptionTranslationPostProcessor matched:
      - @ConditionalOnBooleanProperty (spring.persistence.exceptiontranslation.enabled=true) matched (OnPropertyCondition)
      - @ConditionalOnMissingBean (types: org.springframework.dao.annotation.PersistenceExceptionTranslationPostProcessor; SearchStrategy: all) did not find any beans (OnBeanCondition)

   PropertyPlaceholderAutoConfiguration#propertySourcesPlaceholderConfigurer matched:
      - @ConditionalOnMissingBean (types: org.springframework.context.support.PropertySourcesPlaceholderConfigurer; SearchStrategy: current) did not find any beans (OnBeanCondition)

   SslAutoConfiguration#sslBundleRegistry matched:
      - @ConditionalOnMissingBean (types: org.springframework.boot.ssl.SslBundleRegistry,org.springframework.boot.ssl.SslBundles; SearchStrategy: all) did not find any beans (OnBeanCondition)

   TaskExecutionAutoConfiguration matched:
      - @ConditionalOnClass found required class 'org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor' (OnClassCondition)

   TaskExecutorConfigurations.AsyncConfigurerConfiguration matched:
      - @ConditionalOnMissingBean (types: org.springframework.scheduling.annotation.AsyncConfigurer; SearchStrategy: all) did not find any beans (OnBeanCondition)

   TaskExecutorConfigurations.SimpleAsyncTaskExecutorBuilderConfiguration#simpleAsyncTaskExecutorBuilder matched:
      - @ConditionalOnMissingBean (types: org.springframework.boot.task.SimpleAsyncTaskExecutorBuilder; SearchStrategy: all) did not find any beans (OnBeanCondition)
      - @ConditionalOnThreading found PLATFORM (OnThreadingCondition)

   TaskExecutorConfigurations.TaskExecutorConfiguration matched:
      - AnyNestedCondition 1 matched 1 did not; NestedCondition on TaskExecutorConfigurations.OnExecutorCondition.ModelCondition @ConditionalOnProperty (spring.task.execution.mode=force) did not find property 'spring.task.execution.mode'; NestedCondition on TaskExecutorConfigurations.OnExecutorCondition.ExecutorBeanCondition @ConditionalOnMissingBean (types: java.util.concurrent.Executor; SearchStrategy: all) did not find any beans (TaskExecutorConfigurations.OnExecutorCondition)

   TaskExecutorConfigurations.TaskExecutorConfiguration#applicationTaskExecutor matched:
      - @ConditionalOnThreading found PLATFORM (OnThreadingCondition)

   TaskExecutorConfigurations.ThreadPoolTaskExecutorBuilderConfiguration#threadPoolTaskExecutorBuilder matched:
      - @ConditionalOnMissingBean (types: org.springframework.boot.task.ThreadPoolTaskExecutorBuilder; SearchStrategy: all) did not find any beans (OnBeanCondition)

   TaskSchedulingAutoConfiguration matched:
      - @ConditionalOnClass found required class 'org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler' (OnClassCondition)

   TaskSchedulingConfigurations.SimpleAsyncTaskSchedulerBuilderConfiguration#simpleAsyncTaskSchedulerBuilder matched:
      - @ConditionalOnMissingBean (types: org.springframework.boot.task.SimpleAsyncTaskSchedulerBuilder; SearchStrategy: all) did not find any beans (OnBeanCondition)
      - @ConditionalOnThreading found PLATFORM (OnThreadingCondition)

   TaskSchedulingConfigurations.ThreadPoolTaskSchedulerBuilderConfiguration#threadPoolTaskSchedulerBuilder matched:
      - @ConditionalOnMissingBean (types: org.springframework.boot.task.ThreadPoolTaskSchedulerBuilder; SearchStrategy: all) did not find any beans (OnBeanCondition)

   TomcatServletWebServerAutoConfiguration matched:
      - @ConditionalOnClass found required classes 'jakarta.servlet.ServletRequest', 'org.apache.catalina.startup.Tomcat', 'org.apache.coyote.UpgradeProtocol', 'org.springframework.boot.tomcat.servlet.TomcatServletWebServerFactory' (OnClassCondition)
      - found 'session' scope (OnWebApplicationCondition)

   TomcatServletWebServerAutoConfiguration#tomcatServletWebServerFactory matched:
      - @ConditionalOnMissingBean (types: org.springframework.boot.web.server.servlet.ServletWebServerFactory; SearchStrategy: current) did not find any beans (OnBeanCondition)

   TomcatWebServerConfiguration matched:
      - @ConditionalOnWarDeployment the application is not deployed as a WAR file. (OnWarDeploymentCondition)

   TomcatWebServerConfiguration.TomcatWebSocketConfiguration matched:
      - @ConditionalOnClass found required class 'org.apache.tomcat.websocket.server.WsSci' (OnClassCondition)

   TransactionAutoConfiguration matched:
      - @ConditionalOnClass found required class 'org.springframework.transaction.PlatformTransactionManager' (OnClassCondition)

   TransactionAutoConfiguration.EnableTransactionManagementConfiguration matched:
      - @ConditionalOnBean (types: org.springframework.transaction.TransactionManager; SearchStrategy: all) found bean 'transactionManager'; @ConditionalOnMissingBean (types: org.springframework.transaction.annotation.AbstractTransactionManagementConfiguration; SearchStrategy: all) did not find any beans (OnBeanCondition)

   TransactionAutoConfiguration.EnableTransactionManagementConfiguration.CglibAutoProxyConfiguration matched:
      - @ConditionalOnBooleanProperty (spring.aop.proxy-target-class=true) matched (OnPropertyCondition)

   TransactionAutoConfiguration.TransactionTemplateConfiguration matched:
      - @ConditionalOnSingleCandidate (types: org.springframework.transaction.PlatformTransactionManager; SearchStrategy: all) found a single bean 'transactionManager' (OnBeanCondition)

   TransactionAutoConfiguration.TransactionTemplateConfiguration#transactionTemplate matched:
      - @ConditionalOnMissingBean (types: org.springframework.transaction.support.TransactionOperations; SearchStrategy: all) did not find any beans (OnBeanCondition)

   TransactionManagerCustomizationAutoConfiguration matched:
      - @ConditionalOnClass found required class 'org.springframework.transaction.PlatformTransactionManager' (OnClassCondition)

   TransactionManagerCustomizationAutoConfiguration#platformTransactionManagerCustomizers matched:
      - @ConditionalOnMissingBean (types: org.springframework.boot.transaction.autoconfigure.TransactionManagerCustomizers; SearchStrategy: all) did not find any beans (OnBeanCondition)

   WebMvcAutoConfiguration matched:
      - @ConditionalOnClass found required classes 'jakarta.servlet.Servlet', 'org.springframework.web.servlet.DispatcherServlet', 'org.springframework.web.servlet.config.annotation.WebMvcConfigurer' (OnClassCondition)
      - found 'session' scope (OnWebApplicationCondition)
      - @ConditionalOnMissingBean (types: org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport; SearchStrategy: all) did not find any beans (OnBeanCondition)

   WebMvcAutoConfiguration#formContentFilter matched:
      - @ConditionalOnBooleanProperty (spring.mvc.formcontent.filter.enabled=true) matched (OnPropertyCondition)
      - @ConditionalOnMissingBean (types: org.springframework.web.filter.FormContentFilter; SearchStrategy: all) did not find any beans (OnBeanCondition)

   WebMvcAutoConfiguration.EnableWebMvcConfiguration#flashMapManager matched:
      - @ConditionalOnMissingBean (names: flashMapManager; SearchStrategy: all) did not find any beans (OnBeanCondition)

   WebMvcAutoConfiguration.EnableWebMvcConfiguration#localeResolver matched:
      - @ConditionalOnMissingBean (names: localeResolver; SearchStrategy: all) did not find any beans (OnBeanCondition)

   WebMvcAutoConfiguration.EnableWebMvcConfiguration#viewNameTranslator matched:
      - @ConditionalOnMissingBean (names: viewNameTranslator; SearchStrategy: all) did not find any beans (OnBeanCondition)

   WebMvcAutoConfiguration.WebMvcAutoConfigurationAdapter#defaultViewResolver matched:
      - @ConditionalOnMissingBean (types: org.springframework.web.servlet.view.InternalResourceViewResolver; SearchStrategy: all) did not find any beans (OnBeanCondition)

   WebMvcAutoConfiguration.WebMvcAutoConfigurationAdapter#requestContextFilter matched:
      - @ConditionalOnMissingBean (types: org.springframework.web.context.request.RequestContextListener,org.springframework.web.filter.RequestContextFilter; SearchStrategy: all) did not find any beans (OnBeanCondition)

   WebMvcAutoConfiguration.WebMvcAutoConfigurationAdapter#viewResolver matched:
      - @ConditionalOnBean (types: org.springframework.web.servlet.ViewResolver; SearchStrategy: all) found beans 'defaultViewResolver', 'beanNameViewResolver', 'mvcViewResolver'; @ConditionalOnMissingBean (names: viewResolver types: org.springframework.web.servlet.view.ContentNegotiatingViewResolver; SearchStrategy: all) did not find any beans (OnBeanCondition)


Negative matches:
-----------------

   AopAutoConfiguration.AspectJAutoProxyingConfiguration.JdkDynamicAutoProxyConfiguration:
      Did not match:
         - @ConditionalOnBooleanProperty (spring.aop.proxy-target-class=false) did not find property 'spring.aop.proxy-target-class' (OnPropertyCondition)

   AopAutoConfiguration.ClassProxyingConfiguration:
      Did not match:
         - @ConditionalOnMissingClass found unwanted class 'org.aspectj.weaver.Advice' (OnClassCondition)

   DataJpaRepositoriesAutoConfiguration#entityManagerFactoryBootstrapExecutorCustomizer:
      Did not match:
         - AnyNestedCondition 0 matched 2 did not; NestedCondition on DataJpaRepositoriesAutoConfiguration.BootstrapExecutorCondition.LazyBootstrapMode @ConditionalOnProperty (spring.data.jpa.repositories.bootstrap-mode=lazy) did not find property 'spring.data.jpa.repositories.bootstrap-mode'; NestedCondition on DataJpaRepositoriesAutoConfiguration.BootstrapExecutorCondition.DeferredBootstrapMode @ConditionalOnProperty (spring.data.jpa.repositories.bootstrap-mode=deferred) did not find property 'spring.data.jpa.repositories.bootstrap-mode' (DataJpaRepositoriesAutoConfiguration.BootstrapExecutorCondition)

   DataRepositoryMetricsAutoConfiguration:
      Did not match:
         - @ConditionalOnBean did not find required type 'io.micrometer.core.instrument.MeterRegistry' (OnBeanCondition)

   DataSourceAutoConfiguration.EmbeddedDatabaseConfiguration:
      Did not match:
         - EmbeddedDataSource found supported pooled data source (DataSourceAutoConfiguration.EmbeddedDatabaseCondition)

   DataSourceCheckpointRestoreConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'org.crac.Resource' (OnClassCondition)

   DataSourceConfiguration.Dbcp2:
      Did not match:
         - @ConditionalOnClass did not find required class 'org.apache.commons.dbcp2.BasicDataSource' (OnClassCondition)

   DataSourceConfiguration.Generic:
      Did not match:
         - @ConditionalOnProperty (spring.datasource.type) did not find property 'spring.datasource.type' (OnPropertyCondition)

   DataSourceConfiguration.OracleUcp:
      Did not match:
         - @ConditionalOnClass did not find required classes 'oracle.ucp.jdbc.PoolDataSourceImpl', 'oracle.jdbc.OracleConnection' (OnClassCondition)

   DataSourceConfiguration.Tomcat:
      Did not match:
         - @ConditionalOnClass did not find required class 'org.apache.tomcat.jdbc.pool.DataSource' (OnClassCondition)

   DataSourceHealthContributorAutoConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'org.springframework.boot.health.autoconfigure.contributor.ConditionalOnEnabledHealthIndicator' (OnClassCondition)

   DataSourceJmxConfiguration:
      Did not match:
         - @ConditionalOnBooleanProperty (spring.jmx.enabled=true) did not find property 'spring.jmx.enabled' (OnPropertyCondition)

   DataSourcePoolMetadataProvidersConfiguration.CommonsDbcp2PoolDataSourceMetadataProviderConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'org.apache.commons.dbcp2.BasicDataSource' (OnClassCondition)

   DataSourcePoolMetadataProvidersConfiguration.OracleUcpPoolDataSourceMetadataProviderConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required classes 'oracle.ucp.jdbc.PoolDataSource', 'oracle.jdbc.OracleConnection' (OnClassCondition)

   DataSourcePoolMetadataProvidersConfiguration.TomcatDataSourcePoolMetadataProviderConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'org.apache.tomcat.jdbc.pool.DataSource' (OnClassCondition)

   DataSourcePoolMetricsAutoConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'io.micrometer.core.instrument.MeterRegistry' (OnClassCondition)

   DataSourceTransactionManagerAutoConfiguration.JdbcTransactionManagerConfiguration#transactionManager:
      Did not match:
         - @ConditionalOnMissingBean (types: org.springframework.transaction.TransactionManager; SearchStrategy: all) found beans of type 'org.springframework.transaction.TransactionManager' transactionManager (OnBeanCondition)

   DevToolsR2dbcAutoConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'io.r2dbc.spi.ConnectionFactory' (OnClassCondition)

   DispatcherServletAutoConfiguration.DispatcherServletConfiguration#multipartResolver:
      Did not match:
         - @ConditionalOnBean (types: org.springframework.web.multipart.MultipartResolver; SearchStrategy: all) did not find any beans of type org.springframework.web.multipart.MultipartResolver (OnBeanCondition)

   GsonHttpMessageConvertersConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'com.google.gson.Gson' (OnClassCondition)

   HibernateMetricsAutoConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'io.micrometer.core.instrument.MeterRegistry' (OnClassCondition)

   Jackson2HttpMessageConvertersConfiguration.MappingJackson2HttpMessageConverterConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'com.fasterxml.jackson.databind.ObjectMapper' (OnClassCondition)

   Jackson2HttpMessageConvertersConfiguration.MappingJackson2XmlHttpMessageConverterConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'com.fasterxml.jackson.dataformat.xml.XmlMapper' (OnClassCondition)

   JacksonAutoConfiguration.CborConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'tools.jackson.dataformat.cbor.CBORMapper' (OnClassCondition)

   JacksonAutoConfiguration.XmlConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'tools.jackson.dataformat.xml.XmlMapper' (OnClassCondition)

   JacksonHttpMessageConvertersConfiguration.JacksonXmlHttpMessageConverterConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'tools.jackson.dataformat.xml.XmlMapper' (OnClassCondition)

   JmxAutoConfiguration:
      Did not match:
         - @ConditionalOnBooleanProperty (spring.jmx.enabled=true) did not find property 'spring.jmx.enabled' (OnPropertyCondition)
      Matched:
         - @ConditionalOnClass found required class 'org.springframework.jmx.export.MBeanExporter' (OnClassCondition)

   JndiDataSourceAutoConfiguration:
      Did not match:
         - @ConditionalOnProperty (spring.datasource.jndi-name) did not find property 'spring.datasource.jndi-name' (OnPropertyCondition)
      Matched:
         - @ConditionalOnClass found required classes 'javax.sql.DataSource', 'org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType' (OnClassCondition)

   JndiJtaConfiguration:
      Did not match:
         - @ConditionalOnJndi JNDI environment is not available (OnJndiCondition)
      Matched:
         - @ConditionalOnClass found required class 'org.springframework.transaction.jta.JtaTransactionManager' (OnClassCondition)

   JsonbHttpMessageConvertersConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'jakarta.json.bind.Jsonb' (OnClassCondition)

   KotlinSerializationHttpMessageConvertersConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required classes 'kotlinx.serialization.Serializable', 'kotlinx.serialization.json.Json' (OnClassCondition)

   LocalDevToolsAutoConfiguration.LiveReloadConfiguration:
      Did not match:
         - @ConditionalOnBooleanProperty (spring.devtools.livereload.enabled=true) did not find property 'spring.devtools.livereload.enabled' (OnPropertyCondition)

   MessageSourceAutoConfiguration:
      Did not match:
         - ResourceBundle did not find bundle with basename messages (MessageSourceAutoConfiguration.ResourceBundleCondition)

   ProjectInfoAutoConfiguration#buildProperties:
      Did not match:
         - @ConditionalOnResource did not find resource '${spring.info.build.location:classpath:META-INF/build-info.properties}' (OnResourceCondition)

   ProjectInfoAutoConfiguration#gitProperties:
      Did not match:
         - GitResource did not find git info at classpath:git.properties (ProjectInfoAutoConfiguration.GitResourceAvailableCondition)

   RemoteDevToolsAutoConfiguration:
      Did not match:
         - @ConditionalOnProperty (spring.devtools.remote.secret) did not find property 'spring.devtools.remote.secret' (OnPropertyCondition)
      Matched:
         - @ConditionalOnClass found required classes 'jakarta.servlet.Filter', 'org.springframework.http.server.ServerHttpRequest', 'org.springframework.boot.web.server.autoconfigure.ServerProperties' (OnClassCondition)

   ServletHttpExchangesAutoConfiguration:
      Did not match:
         - @ConditionalOnBean did not find required type 'org.springframework.boot.actuate.web.exchanges.HttpExchangeRepository' (OnBeanCondition)

   ServletManagementContextAutoConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'org.springframework.boot.actuate.autoconfigure.endpoint.web.WebEndpointProperties' (OnClassCondition)

   ServletMappingsAutoConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'org.springframework.boot.actuate.autoconfigure.endpoint.condition.ConditionalOnAvailableEndpoint' (OnClassCondition)

   ServletWebServerConfiguration#forwardedHeaderFilter:
      Did not match:
         - @ConditionalOnProperty (server.forward-headers-strategy=framework) did not find property 'server.forward-headers-strategy' (OnPropertyCondition)

   SpringApplicationAdminJmxAutoConfiguration:
      Did not match:
         - @ConditionalOnBooleanProperty (spring.application.admin.enabled=true) did not find property 'spring.application.admin.enabled' (OnPropertyCondition)

   TaskExecutorConfigurations.AsyncConfigurerWrapperConfiguration:
      Did not match:
         - @ConditionalOnBean (types: org.springframework.scheduling.annotation.AsyncConfigurer; SearchStrategy: all) did not find any beans of type org.springframework.scheduling.annotation.AsyncConfigurer (OnBeanCondition)

   TaskExecutorConfigurations.SimpleAsyncTaskExecutorBuilderConfiguration#simpleAsyncTaskExecutorBuilderVirtualThreads:
      Did not match:
         - @ConditionalOnMissingBean (types: org.springframework.boot.task.SimpleAsyncTaskExecutorBuilder; SearchStrategy: all) found beans of type 'org.springframework.boot.task.SimpleAsyncTaskExecutorBuilder' simpleAsyncTaskExecutorBuilder (OnBeanCondition)

   TaskExecutorConfigurations.TaskExecutorConfiguration#applicationTaskExecutorVirtualThreads:
      Did not match:
         - @ConditionalOnThreading did not find VIRTUAL (OnThreadingCondition)

   TaskSchedulingAutoConfiguration#scheduledBeanLazyInitializationExcludeFilter:
      Did not match:
         - @ConditionalOnBean (names: org.springframework.scheduling.config.internalScheduledAnnotationProcessor; SearchStrategy: all) did not find any beans named org.springframework.scheduling.config.internalScheduledAnnotationProcessor (OnBeanCondition)

   TaskSchedulingConfigurations.SimpleAsyncTaskSchedulerBuilderConfiguration#simpleAsyncTaskSchedulerBuilderVirtualThreads:
      Did not match:
         - @ConditionalOnMissingBean (types: org.springframework.boot.task.SimpleAsyncTaskSchedulerBuilder; SearchStrategy: all) found beans of type 'org.springframework.boot.task.SimpleAsyncTaskSchedulerBuilder' simpleAsyncTaskSchedulerBuilder (OnBeanCondition)

   TaskSchedulingConfigurations.TaskSchedulerConfiguration:
      Did not match:
         - @ConditionalOnBean (names: org.springframework.scheduling.config.internalScheduledAnnotationProcessor; SearchStrategy: all) did not find any beans named org.springframework.scheduling.config.internalScheduledAnnotationProcessor (OnBeanCondition)

   TomcatMetricsAutoConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'io.micrometer.core.instrument.binder.tomcat.TomcatMetrics' (OnClassCondition)

   TomcatReactiveManagementContextAutoConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextFactory' (OnClassCondition)

   TomcatReactiveWebServerAutoConfiguration:
      Did not match:
         - @ConditionalOnWebApplication did not find reactive web application classes (OnWebApplicationCondition)

   TomcatServletManagementContextAutoConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextFactory' (OnClassCondition)

   TomcatServletWebServerAutoConfiguration#tomcatForwardedHeaderFilterCustomizer:
      Did not match:
         - @ConditionalOnProperty (server.forward-headers-strategy=framework) did not find property 'server.forward-headers-strategy' (OnPropertyCondition)

   TomcatWebServerConfiguration#tomcatVirtualThreadsProtocolHandlerCustomizer:
      Did not match:
         - @ConditionalOnThreading did not find VIRTUAL (OnThreadingCondition)

   TransactionAutoConfiguration#transactionalOperator:
      Did not match:
         - @ConditionalOnSingleCandidate (types: org.springframework.transaction.ReactiveTransactionManager; SearchStrategy: all) did not find any beans (OnBeanCondition)

   TransactionAutoConfiguration.AspectJTransactionManagementConfiguration:
      Did not match:
         - @ConditionalOnBean (types: org.springframework.transaction.aspectj.AbstractTransactionAspect; SearchStrategy: all) did not find any beans of type org.springframework.transaction.aspectj.AbstractTransactionAspect (OnBeanCondition)

   TransactionAutoConfiguration.EnableTransactionManagementConfiguration.JdkDynamicAutoProxyConfiguration:
      Did not match:
         - @ConditionalOnBooleanProperty (spring.aop.proxy-target-class=false) did not find property 'spring.aop.proxy-target-class' (OnPropertyCondition)

   WebMvcAutoConfiguration#hiddenHttpMethodFilter:
      Did not match:
         - @ConditionalOnBooleanProperty (spring.mvc.hiddenmethod.filter.enabled=true) did not find property 'spring.mvc.hiddenmethod.filter.enabled' (OnPropertyCondition)

   WebMvcAutoConfiguration.ProblemDetailsErrorHandlingConfiguration:
      Did not match:
         - @ConditionalOnBooleanProperty (spring.mvc.problemdetails.enabled=true) did not find property 'spring.mvc.problemdetails.enabled' (OnPropertyCondition)

   WebMvcAutoConfiguration.ResourceChainCustomizerConfiguration:
      Did not match:
         - @ConditionalOnEnabledResourceChain did not find class org.webjars.WebJarVersionLocator (OnEnabledResourceChainCondition)

   WebMvcAutoConfiguration.WebMvcAutoConfigurationAdapter#beanNameViewResolver:
      Did not match:
         - @ConditionalOnMissingBean (types: org.springframework.web.servlet.view.BeanNameViewResolver; SearchStrategy: all) found beans of type 'org.springframework.web.servlet.view.BeanNameViewResolver' beanNameViewResolver (OnBeanCondition)

   WebMvcHealthEndpointExtensionAutoConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'org.springframework.boot.health.actuate.endpoint.HealthEndpoint' (OnClassCondition)

   WebMvcMappingsAutoConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'org.springframework.boot.actuate.autoconfigure.endpoint.condition.ConditionalOnAvailableEndpoint' (OnClassCondition)

   WebMvcObservationAutoConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required class 'org.springframework.boot.micrometer.observation.autoconfigure.ObservationProperties' (OnClassCondition)

   XADataSourceAutoConfiguration:
      Did not match:
         - @ConditionalOnBean (types: org.springframework.boot.jdbc.XADataSourceWrapper; SearchStrategy: all) did not find any beans of type org.springframework.boot.jdbc.XADataSourceWrapper (OnBeanCondition)
      Matched:
         - @ConditionalOnClass found required classes 'javax.sql.DataSource', 'jakarta.transaction.TransactionManager', 'org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType' (OnClassCondition)


Exclusions:
-----------

    None


Unconditional classes:
----------------------

    org.springframework.boot.autoconfigure.context.ConfigurationPropertiesAutoConfiguration

    org.springframework.boot.autoconfigure.ssl.SslAutoConfiguration

    org.springframework.boot.autoconfigure.context.LifecycleAutoConfiguration

    org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration

    org.springframework.boot.autoconfigure.availability.ApplicationAvailabilityAutoConfiguration

    org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration



2026-03-31T23:50:25.253-07:00  INFO 13925 --- [restful-webservices] [restartedMain] c.e.r.RestfulWebservicesApplication      : Started RestfulWebservicesApplication in 0.327 seconds (process running for 944.034)
2026-03-31T23:50:25.253-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.a.ApplicationAvailabilityBean      : Application availability state LivenessState changed to CORRECT
2026-03-31T23:50:25.254-07:00  INFO 13925 --- [restful-webservices] [restartedMain] .ConditionEvaluationDeltaLoggingListener : Condition evaluation unchanged
2026-03-31T23:50:25.254-07:00 DEBUG 13925 --- [restful-webservices] [restartedMain] o.s.b.a.ApplicationAvailabilityBean      : Application availability state ReadinessState changed to ACCEPTING_TRAFFIC
2026-03-31T23:50:39.788-07:00  INFO 13925 --- [restful-webservices] [File Watcher] rtingClassPathChangeChangedEventListener : Restarting due to 1 class path change (0 additions, 0 deletions, 1 modification)
2026-03-31T23:50:39.789-07:00 DEBUG 13925 --- [restful-webservices] [File Watcher] rtingClassPathChangeChangedEventListener : Change set: [/Users/pranavsangu/Documents/Vscode/java/spring_vscode/restful-webservices/target/classes [/Users/pranavsangu/Documents/Vscode/java/spring_vscode/restful-webservices/target/classes/application.properties (MODIFY)]]
2026-03-31T23:50:39.789-07:00 DEBUG 13925 --- [restful-webservices] [File Watcher] o.s.boot.devtools.restart.Restarter      : Restarting application
2026-03-31T23:50:39.790-07:00 DEBUG 13925 --- [restful-webservices] [Thread-22] o.s.boot.devtools.restart.Restarter      : Stopping application
2026-03-31T23:50:39.790-07:00 DEBUG 13925 --- [restful-webservices] [Thread-22] o.s.b.a.ApplicationAvailabilityBean      : Application availability state ReadinessState changed from ACCEPTING_TRAFFIC to REFUSING_TRAFFIC
2026-03-31T23:50:39.790-07:00 DEBUG 13925 --- [restful-webservices] [Thread-22] ConfigServletWebServerApplicationContext : Closing org.springframework.boot.web.server.servlet.context.AnnotationConfigServletWebServerApplicationContext@554157f6, started on Tue Mar 31 23:50:24 PDT 2026
2026-03-31T23:50:39.792-07:00 DEBUG 13925 --- [restful-webservices] [Thread-22] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147482623
2026-03-31T23:50:39.792-07:00  INFO 13925 --- [restful-webservices] [Thread-22] o.s.boot.tomcat.GracefulShutdown         : Commencing graceful shutdown. Waiting for active requests to complete
2026-03-31T23:50:39.794-07:00  INFO 13925 --- [restful-webservices] [tomcat-shutdown] o.s.boot.tomcat.GracefulShutdown         : Graceful shutdown complete
2026-03-31T23:50:39.794-07:00 DEBUG 13925 --- [restful-webservices] [tomcat-shutdown] o.s.c.support.DefaultLifecycleProcessor  : Bean 'webServerGracefulShutdown' completed its stop procedure
2026-03-31T23:50:39.794-07:00 DEBUG 13925 --- [restful-webservices] [Thread-22] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147481599
2026-03-31T23:50:39.795-07:00 DEBUG 13925 --- [restful-webservices] [Thread-22] o.s.c.support.DefaultLifecycleProcessor  : Bean 'webServerStartStop' completed its stop procedure
2026-03-31T23:50:39.796-07:00 DEBUG 13925 --- [restful-webservices] [Thread-22] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 1073741823
2026-03-31T23:50:39.796-07:00 DEBUG 13925 --- [restful-webservices] [Thread-22] o.s.c.support.DefaultLifecycleProcessor  : Bean 'applicationTaskExecutor' completed its stop procedure
2026-03-31T23:50:39.796-07:00 DEBUG 13925 --- [restful-webservices] [Thread-22] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase -2147483647
2026-03-31T23:50:39.800-07:00 DEBUG 13925 --- [restful-webservices] [Thread-22] o.s.c.support.DefaultLifecycleProcessor  : Bean 'springBootLoggingLifecycle' completed its stop procedure
2026-03-31T23:50:39.804-07:00  INFO 13925 --- [restful-webservices] [Thread-22] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2026-03-31T23:50:39.819-07:00  WARN 13925 --- [restful-webservices] [Thread-22] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method failed on bean with name 'inMemoryDatabaseShutdownExecutor'

org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-240]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690) ~[h2-2.4.240.jar:2.4.240]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489) ~[h2-2.4.240.jar:2.4.240]
	at org.h2.message.DbException.get(DbException.java:223) ~[h2-2.4.240.jar:2.4.240]
	at org.h2.message.DbException.get(DbException.java:199) ~[h2-2.4.240.jar:2.4.240]
	at org.h2.message.DbException.get(DbException.java:188) ~[h2-2.4.240.jar:2.4.240]
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1418) ~[h2-2.4.240.jar:2.4.240]
	at org.h2.jdbc.JdbcConnection.clearWarnings(JdbcConnection.java:657) ~[h2-2.4.240.jar:2.4.240]
	at com.zaxxer.hikari.pool.ProxyConnection.close(ProxyConnection.java:258) ~[HikariCP-7.0.2.jar:na]
	at org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration$NonEmbeddedInMemoryDatabaseShutdownExecutor$InMemoryDatabase.lambda$new$0(DevToolsDataSourceAutoConfiguration.java:154) ~[spring-boot-devtools-4.0.4.jar:4.0.4]
	at org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration$NonEmbeddedInMemoryDatabaseShutdownExecutor$InMemoryDatabase.shutdown(DevToolsDataSourceAutoConfiguration.java:172) ~[spring-boot-devtools-4.0.4.jar:4.0.4]
	at org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration$NonEmbeddedInMemoryDatabaseShutdownExecutor.destroy(DevToolsDataSourceAutoConfiguration.java:114) ~[spring-boot-devtools-4.0.4.jar:4.0.4]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:209) ~[spring-beans-7.0.6.jar:7.0.6]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:795) ~[spring-beans-7.0.6.jar:7.0.6]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:745) ~[spring-beans-7.0.6.jar:7.0.6]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1500) ~[spring-beans-7.0.6.jar:7.0.6]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:704) ~[spring-beans-7.0.6.jar:7.0.6]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1493) ~[spring-beans-7.0.6.jar:7.0.6]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1246) ~[spring-context-7.0.6.jar:7.0.6]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1207) ~[spring-context-7.0.6.jar:7.0.6]
	at org.springframework.boot.web.server.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:176) ~[spring-boot-web-server-4.0.4.jar:4.0.4]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1153) ~[spring-context-7.0.6.jar:7.0.6]
	at org.springframework.boot.devtools.restart.Restarter.stop(Restarter.java:310) ~[spring-boot-devtools-4.0.4.jar:4.0.4]
	at org.springframework.boot.devtools.restart.Restarter.lambda$restart$0(Restarter.java:251) ~[spring-boot-devtools-4.0.4.jar:4.0.4]
	at org.springframework.boot.devtools.restart.Restarter$LeakSafeThread.run(Restarter.java:616) ~[spring-boot-devtools-4.0.4.jar:4.0.4]

2026-03-31T23:50:39.824-07:00  INFO 13925 --- [restful-webservices] [Thread-22] com.zaxxer.hikari.HikariDataSource       : HikariPool-6 - Shutdown initiated...
2026-03-31T23:50:39.825-07:00  INFO 13925 --- [restful-webservices] [Thread-22] com.zaxxer.hikari.HikariDataSource       : HikariPool-6 - Shutdown completed.
2026-03-31T23:50:39.825-07:00 DEBUG 13925 --- [restful-webservices] [Thread-22] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2026-03-31T23:50:39.914-07:00 DEBUG 13925 --- [restful-webservices] [Thread-22] o.s.boot.devtools.restart.Restarter      : Starting application com.example_web_services.restful_webservices.RestfulWebservicesApplication with URLs [file:/Users/pranavsangu/Documents/Vscode/java/spring_vscode/restful-webservices/target/classes/]
