spring.application.name=restful-webservices
logging.level.org.springframework= info
management.endpoints.web.exposure.include=*
spring.h2.console.enabled=true
# spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql= true
spring.datasource.url=jdbc:mysql://localhost:3307/social-media-database
spring.datasource.username= social-media-user
spring.datasource.password=dummypassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
spring.security.user.name= user
spring.security.user.password=password

# docker run -d \
#   --env MYSQL_ROOT_PASSWORD=toor \
#   --env MYSQL_USER=social-media-user \
#   --env MYSQL_PASSWORD=dummypassword \
#   --env MYSQL_DATABASE=social-media-database \
#   --name mysql \
#   -p 3307:3306 \
#   mysql:8-oracle

# spring.mvc.apiversion.use.query-parameter=version
# spring.mvc.apiversion.use.path-segment=0
# spring.mvc.apiversion.use.header= X-API-VERSION
# spring.mvc.apiversion.use.media-type-parameter[application/json]=version
# #Accept:application/json;version=2
# spring.web.error.include-message=never
# spring.web.error.include-binding-errors=never
# spring.web.error.include-stacktrace=never
#spring.web.error.whitelabel.enabled=false
#logging.file.name=app.log
